# -*- coding: utf-8 -*-
"""COMPANY · ORGANIZATION · ROLES · PEOPLE · SYSTEMS · SALES/OPERATIONS/PEOPLE models · CONFLICTS.
Every entry carries `src` (source ids) and `conf` ∈ CONFIRMED · DERIVED · UNVERIFIED · UNKNOWN. UNKNOWN stays UNKNOWN."""

def F(value, src, conf="CONFIRMED", note=None):
    d = {"value": value, "src": list(src) if isinstance(src, (list, tuple)) else [src], "conf": conf}
    if note: d["note"] = note
    return d

UNKNOWN = lambda note=None, src=(): F("UNKNOWN", src, "UNKNOWN", note)

COMPANY = {
 "name": F("HouseNet LLC (ՀաուսՆեթ ՍՊԸ)", ["S01", "S02", "S03"]),
 "purpose": F("Internet service provider (FTTH/GPON, EOC, CATV/IPTV) on its own already-built network; strategy = density on the network, not price", ["S02", "S03"]),
 "products": F(["Plus 7000 (50 Mbit/s, 7,000 AMD/month — dominant new-sales package)", "EOC Combo Prime 30 Mbit/s (7,000)", "EOC Combo Start 20 Mbit/s (6,000)", "Lite 6000 (20 Mbit)", "iPlus 5500 (40 Mbit)", "iLite 4,900", "Corporate 40 Mbit/s yearly subscription (postpaid)", "CATV / IPTV, Wi-Fi/CPE services"], ["S03", "S05"]),
 "customer_types": F(["Residential subscribers (B2C, monthly or yearly agreement)", "Corporate / legal entities (postpaid, bank transfer, ՀՎՀՀ required for reconciliation)"], ["S05", "S07"]),
 "geography": F(["Արմավիր (primary branch, phase-1 focus)", "Մեծամոր", "Էջմիածին", "Նորապատ (subscribers present)"], ["S03", "S05"], note="Armavir region, Armenia"),
 "channels": F(["3 branch sales & service offices (Վաճառքի և սպասարկման գրասենյակ)", "Telesales (outbound, PBX)", "D2D field agents (sector-based)", "Marketing leads (paid ads, SMM) → Sales/Call center", "Call center inbound (up-sell/cross-sell without pressure)", "Corporate — no dedicated person or process (GAP)"], ["S01", "S02", "S03"]),
 "operational_functions": F(["Կոմերցիոն (Sales + Marketing)", "Տեխնիկական (in-home service, installation, network build, technical support: provisioning/warehouse/NOC/L2)", "Հաճախորդների սպասարկում (call center, L&R retention/quality)", "Բիլինգ և եկամուտ (billing, collections, revenue protection, reporting)"], ["S01", "S02"]),
 "headcount": F({"positions": 52, "filled": 25, "vacant": 27, "critical_vacant": 13, "important_vacant": 6, "can_wait_vacant": 8, "contractors": 2, "executives_outside_table": 3, "total_structure": 57}, "S01"),
 "payroll": F("CONFIDENTIAL — monthly payroll figures live in the sensitive overlay (compensation table)", "S01", note="overlay ref: compensation.payroll"),
}

FUNCTIONS = [
 {"id": "FN-COM", "name": "Կոմերցիոն", "purpose": "New subscriber acquisition and revenue growth via branches, telesales, D2D and marketing", "accountable_role": "Վաճառքի ղեկավար (1.1) — sales; Մարքեթինգի ղեկավար (1.7) — marketing; both report to Վաճառքի և գործառնական ղեկավար",
  "roles": ["1.1", "1.2", "1.3", "1.4", "1.5", "1.6", "1.7", "1.8", "1.9"], "headcount": F({"positions": 19, "filled": 6}, "S01"),
  "upstream": ["Marketing leads", "Call-center leads", "Network coverage (Ցանցի կառուցում)"], "downstream": ["Installation (Տեղադրում) — connection SLA", "Billing — activation, tariff attach", "Call center — application registration"], "src": ["S01", "S02"], "conf": "CONFIRMED"},
 {"id": "FN-TECH", "name": "Տեխնիկական", "purpose": "Connect and keep subscribers connected: installation, in-home repair, network build/repair, provisioning, warehouse, NOC, L2", "accountable_role": "Տեխնիկական բաժնի ղեկավար (CTO) — outside staffing table",
  "roles": ["2.1", "2.2", "2.3", "2.4", "2.5", "2.6", "2.7", "2.8", "2.9", "2.10", "2.11", "2.12", "2.13", "2.14"], "headcount": F({"positions": 22, "filled": 13}, "S01"),
  "upstream": ["Sales — connection applications", "Call center — fault applications (L1)", "NOC alerts"], "downstream": ["Billing — technical handoff (BILL-03)", "Call center — status/SLA to subscriber"], "src": ["S01", "S02"], "conf": "CONFIRMED"},
 {"id": "FN-CS", "name": "Հաճախորդների սպասարկում", "purpose": "First contact quality, application registration, complaints, retention (L&R)", "accountable_role": "Հաճախորդների սպասարկման ղեկավար (+ՈԱ +Բողոք/Պահպանում) (3.1) → Վաճառքի և գործառնական ղեկավար",
  "roles": ["3.1", "3.2", "3.3", "3.4"], "headcount": F({"positions": 9, "filled": 5}, "S01"),
  "upstream": ["Inbound calls", "Marketing/SMM leads", "Billing collections tasking"], "downstream": ["L2 / field teams — applications", "Sales — leads", "Billing — payment questions"], "src": ["S01", "S02"], "conf": "CONFIRMED"},
 {"id": "FN-BILL", "name": "Բիլինգ և եկամուտ", "purpose": "Billing accuracy, revenue protection, collections, month-end closing/reconciliation, reporting", "accountable_role": "Բիլինգի և եկամտի ղեկավար (+Համադրում/Աուդիտ) (4.1) → Վաճառքի և գործառնական ղեկավար (S01/S02); roadmap says CEO/COO/CFO (C08)",
  "roles": ["4.1", "4.2"], "headcount": F({"positions": 2, "filled": 1}, "S01"),
  "upstream": ["Technical handoff", "Sales — tariffs/discounts", "Payments (banks, cash, inspectors)"], "downstream": ["Call center — collections tasking", "Management — reports", "Finance — reconciliation"], "src": ["S01", "S02", "S04"], "conf": "CONFIRMED"},
 {"id": "FN-EXEC", "name": "Ղեկավարություն", "purpose": "CEO (Գործադիր տնօրեն), CTO (Տեխնիկական բաժնի ղեկավար), S&O (Վաճառքի և գործառնական ղեկավար = Gev) — outside the staffing table", "accountable_role": "CEO",
  "roles": ["EXEC-CEO", "EXEC-CTO", "EXEC-SO"], "headcount": F({"positions": 3}, "S01"), "upstream": [], "downstream": ["all functions"], "src": ["S01", "S02"], "conf": "CONFIRMED"},
]

# ROLES — the 29 staffing/JD cards (+3 execs +2 contractors). Compensation is NOT here (overlay). kpi ids → bm_kpis.ROLE_KPIS
def R(code, title, fn, manager, reports, count, filled, priority, fix, purpose, decides, escalates, inputs, outputs, deps, nature, conf="CONFIRMED", src=("S01", "S02"), note=None):
    # `fix` is accepted for authoring compatibility but NEVER stored: compensation lives in overlay/ov_compensation.py (CONFIDENTIAL)
    d = {"code": code, "title": title, "function": fn, "manager": manager, "reports": reports, "positions": count, "filled": filled, "vacancy_priority": priority,
         "compensation": "OVERLAY", "purpose": purpose, "decision_rights": decides, "escalation_path": escalates, "inputs": inputs, "outputs": outputs,
         "dependencies": deps, "work_nature": nature, "kpis": f"ROLE_KPIS[{code!r}]", "src": list(src), "conf": conf}
    if note: d["note"] = note
    return d

ROLES = [
 R("1.1", "Վաճառքի ղեկավար", "FN-COM", "Վաճառքի և գործառնական ղեկավար", ["1.2 ×3", "1.4 ×1", "1.6 ×6"], 1, 1, "Համալրված", 0,
   "Run the sales department: monthly split of the approved annual plan, control of offices/telesales/D2D, CRM & reporting quality, hiring/coaching",
   ["monthly plan split across offices/channels", "priorities & assignments inside the department", "coaching/corrective actions"],
   ["plan/budget/pricing/tariff changes → Վաճառքի և գործառնական ղեկավար", "cross-department or company-level issues", "HR decisions outside authority"],
   ["approved annual sales plan", "CRM data", "leads from marketing"], ["plan execution", "sales reports/recommendations", "hiring decisions (with S&O)"],
   ["Marketing (leads)", "Customer service (complaints/retention)", "Billing (activation, tariffs, debts)", "Technical (connection lead time)"], "office",
   note="Also runs recruiting while the recruiter contractor is vacant (S03)."),
 R("1.2", "Վաճառքի և սպասարկման ավագ մասնագետ", "FN-COM", "1.1 Վաճառքի ղեկավար", ["1.3 ×3"], 3, 3, "Համալրված", 0,
   "Personal sales + service and operational coordination of one branch office", ["daily office work distribution", "standard sales/service cases within approved rules"],
   ["repeated/disciplinary issues → 1.1", "complaints outside procedure", "pricing/contract exceptions"], ["customers", "CRM", "leads"], ["activated sales", "office control", "CRM quality"], ["Call center", "Installation", "Billing"], "mixed"),
 R("1.3", "Վաճառքի մասնագետ", "FN-COM", "1.2", [], 3, 0, "Կրիտիկական", 0, "Sell and serve: need discovery → offer → close → CRM → application handoff",
   ["offer within approved tariffs/promos", "next steps of standard cases", "follow-up timing"], ["complex complaints/exceptions → 1.2 or 1.1", "technical issues → technical unit via application"], ["customers", "tariff sheet"], ["closed sales", "applications", "CRM records"], ["Call center", "Installation", "Billing"], "mixed"),
 R("1.4", "Հեռախոսային վաճառքի ավագ մասնագետ", "FN-COM", "1.1", ["1.5 ×2"], 1, 1, "Համալրված", 0, "Outbound telesales on the provided base + coordination/QA of telesales agents",
   ["agents' work distribution", "call sampling/feedback", "own sales within approved scripts"], ["repeated issues → 1.1", "exceptions", "CRM/PBX/base system problems"], ["lead base (≥1,500 numbers for 2 agents — S03)", "PBX", "CRM"], ["telesales", "call quality", "escalations"], ["Marketing (lead base)", "Call center (inbound leads)", "Billing"], "office",
   note="Per Gev (S08 09-09 12:44) the telesales senior also reports retention calls to @P5 (daily if red, weekly standard) — unconfirmed by @P1."),
 R("1.5", "Հեռախոսային վաճառքի գործակալ", "FN-COM", "1.4", [], 2, 0, "Կրիտիկական", 0, "Outbound calls on the provided base to close sales", ["variant within approved tariffs/scripts", "follow-up step"], ["complex cases → 1.4/1.1"], ["base", "PBX", "CRM"], ["telesales (activated)", "CRM records"], ["Call center", "Installation", "Billing"], "office"),
 R("1.6", "D2D գործակալ", "FN-COM", "1.1", [], 6, 0, "Կրիտիկական", 0, "Field door-to-door sales on pre-assigned addresses/sectors; qualified applications only",
   ["first contact/conversation within D2D script", "preliminary qualification", "refuse to pass an unqualified application"], ["complaints/conflicts → 1.1", "address/coverage uncertainty", "missing mandatory data"], ["sector map & address list (S03: mandatory before day 13)"], ["qualified applications", "visit records"], ["Installation", "Call center", "Billing"], "field",
   note="Pay model Բ: fix 70,000 only when ≥80% of plan; +100% of sold tariffs, no ceiling. No KPI weights (S01)."),
 R("1.7", "Մարքեթինգի ղեկավար", "FN-COM", "Վաճառքի և գործառնական ղեկավար", ["1.8", "1.9"], 1, 1, "Համալրված", 0, "Controllable customer acquisition, budget, brand, retention marketing, Marketing–Sales alignment",
   ["campaign structure/channel mix within budget", "stop ineffective creatives", "suspend unapproved communication"], ["budget/strategy → S&O head"], ["budget", "CRM", "ads data"], ["campaigns", "leads", "weekly/monthly reports"], ["Sales (lead handoff, Lead Response SLA)", "Customer service (retention)", "Billing (tariff validation)"], "office"),
 R("1.8", "Performance Marketing մասնագետ", "FN-COM", "1.7", [], 1, 0, "Կարող է սպասել", 0, "Paid acquisition with controllable CAC/CPL/ROAS", ["optimization within budget", "pause ineffective ads"], ["tracking failure/wrong tariff → immediate escalation to 1.7"], ["budget", "ads platforms"], ["leads", "performance reports"], ["Sales/Call center (lead quality)", "Technical (site/tracking)"], "office"),
 R("1.9", "SMM մասնագետ", "FN-COM", "1.7", [], 1, 0, "Կարևոր", 0, "Organic social presence, content plan, community management", ["content within approved plan", "low-risk replies"], ["sensitive complaints/crisis → 1.7"], ["content plan"], ["posts, social leads", "content reports"], ["Performance marketing", "Call center", "Sales"], "office"),
 R("2.1", "Ներտնային սպասարկման խմբի ղեկավար", "FN-TECH", "Տեխնիկական բաժնի ղեկավար", ["2.2 ×2"], 1, 1, "Համալրված", 0, "Quality of in-home repair visits, RCA of repeats, engineer skills", ["device replacement decisions", "return a poorly closed application"], ["network cause → L2", "deadline risk → dispatcher (vacant → CTO)", "mass outage signs → NOC"], ["CRM applications"], ["closed applications", "RCA"], ["Call center", "L2", "NOC", "Provisioning"], "field"),
 R("2.2", "Ներտնային սպասարկման մասնագետ", "FN-TECH", "2.1", [], 2, 1, "Կարող է սպասել", 0, "Diagnose and fix subscriber-side issues on site per SLA", ["standard CPE replacement", "repair method within SOP"], ["network cause → L2", "SLA risk → dispatcher/CTO", "repeat/≥2 CPE → 2.1"], ["dispatcher tasks"], ["closed applications with serial/mac/measurements"], ["Dispatcher/Call center", "L2", "Provisioning"], "field"),
 R("2.3", "Տեղադրման խմբի ղեկավար", "FN-TECH", "Տեխնիկական բաժնի ղեկավար", ["2.4 ×3", "2.5 ×3"], 1, 0, "Կարևոր", 0, "Installation quality and new-connection SLA", ["reassignment request", "reject poor closure", "approve non-standard solution"], [], ["sales applications"], ["activated connections"], ["Sales (application accuracy)", "Dispatcher/CTO", "Network build", "Provisioning"], "field", note="VACANT — installation queue ownership falls to CTO until filled."),
 R("2.4", "Տեղադրման ավագ մասնագետ", "FN-TECH", "2.3", [], 3, 0, "Կարող է սպասել", 0, "Complex installations + mentoring installers", ["CPE point/drop route", "return junior's work", "stop work on safety risk"], ["SLA risk → dispatcher", "standard deviation → 2.3", "no building signal → network build"], [], [], [], "field"),
 R("2.5", "Տեղադրման մասնագետ", "FN-TECH", "2.3", [], 3, 2, "Կրիտիկական", 0, "New subscriber installation and first service start", ["CPE point/route with subscriber", "request materials", "stop on safety risk"], ["SLA/no access → dispatcher (vacant → CTO)", "non-standard → senior (vacant → CTO)", "building signal → line engineer"], ["tasks", "CPE/materials"], ["installations closed in CRM"], ["Dispatcher", "Network build", "Provisioning"], "field"),
 R("2.6", "Ցանցի կառուցման խմբի ղեկավար", "FN-TECH", "Տեխնիկական բաժնի ղեկավար", ["2.7 ×2", "2.8 ×2", "2.9", "2.10"], 1, 1, "Համալրված", 0, "Network expansion/build and line fault restoration within SLA", ["route design changes", "reject line acceptance", "reject poor closure"], ["trunk break/mass fault → NOC + CTO", "reassignment → dispatcher", "materials/permits → CTO"], ["expansion program"], ["built/accepted lines", "RCA"], ["NOC", "Dispatcher", "Installation", "Contractors/municipalities"], "mixed"),
 R("2.7", "Լարանցման ավագ մասնագետ", "FN-TECH", "2.6", [], 2, 1, "Կարող է սպասել", 0, "Coordinate the build brigade; acceptance measurements", ["temporary→permanent solution", "local route deviation", "stop unsafe work"], ["design revision → 2.6", "trunk SLA risk → dispatcher/CTO", "repeat fault → RCA"], [], [], [], "field"),
 R("2.8", "Լարանցման մասնագետ", "FN-TECH", "2.6", [], 2, 2, "Համալրված", 0, "Outdoor optical/RG network build, prevention and fault restoration", ["temporary restoration method", "stop on safety risk"], ["cable break → senior + NOC", "deadline risk → dispatcher/CTO"], [], [], [], "field"),
 R("2.9", "Եռակցման ավագ մասնագետ", "FN-TECH", "2.6", [], 1, 1, "Համալրված", 0, "Complex splicing; acceptance at ≤0.05 dB; splice documentation", ["reject acceptance >0.05 dB", "stop unsafe work", "splicing order"], ["trunk fault → senior line engineer + NOC"], [], [], [], "field"),
 R("2.10", "Եռակցման մասնագետ", "FN-TECH", "2.6", [], 1, 1, "Համալրված", 0, "Fiber splicing/termination/measurement", ["re-splice on deviation"], ["loss >0.05 dB → senior splicer"], [], [], [], "field"),
 R("2.11", "Սարքավորումների կարգավորման մասնագետ", "FN-TECH", "Տեխնիկական բաժնի ղեկավար", [], 1, 1, "Համալրված", 0, "CPE pre-configuration; device↔subscriber/warehouse data in billing and OLT", ["reject mismatched binding", "reuse/write-off", "firmware update"], ["billing/device mismatch blocking activation → CTO + billing", "stock below minimum → CTO"], [], ["configured CPE", "returned-CPE register"], ["Installation/in-home teams", "Billing", "L2", "Warehouse"], "office"),
 R("2.12", "Ապրանքանյութական արժեքների պատասխանատու", "FN-TECH", "Տեխնիկական բաժնի ղեկավար", [], 1, 0, "Կարևոր", 0, "Warehouse: intake, issue, returns, inventory, minimum stock", ["refuse issue without approved task", "returned material fitness"], ["below minimum stock / loss → CTO", "document mismatch → accounting"], [], [], [], "office"),
 R("2.13", "NOC, Մոնիտորինգի և Backup մասնագետ", "FN-TECH", "Տեխնիկական բաժնի ղեկավար", [], 1, 1, "Համալրված", 0, "24/7 monitoring, incident classification ≤5 min, backups/DR", ["alert severity", "rerun backups", "close incident after monitoring confirms"], ["mass outage → CTO + Call center immediately", "line fault alert → senior line engineer + dispatcher ≤15 min", "2 days backup failure → CTO"], [], ["incidents in CRM", "RCA"], ["Call center", "Network build", "L2", "Dispatcher"], "office 24/7"),
 R("2.14", "L2 մասնագետ", "FN-TECH", "Տեխնիկական բաժնի ղեկավար", [], 2, 1, "Կարող է սպասել", 0, "Remote advanced diagnosis of issues the call center cannot close", ["ONU/CPE profile change within scope", "field visit necessity", "close/escalate own application"], ["mass incident → NOC", "no remote fix → dispatcher (vacant → CTO)", "vendor/SLA-breach risk → L2 senior"], ["L1 applications"], ["remotely solved applications"], ["Call center", "Field teams", "NOC", "Billing"], "office"),
 R("3.1", "Հաճախորդների սպասարկման ղեկավար (+ՈԱ +Բողոք/Պահպանում)", "FN-CS", "Վաճառքի և գործառնական ղեկավար", ["3.2", "3.3"], 1, 1, "Համալրված", 0, "Call-center quality, call/application flow, complaints and retention",
   ["schedules/shifts", "SOPs/QA checklist", "training needs", "retention benefits list within budget"], ["hiring/out-of-budget/structure → Գործադիր տնօրեն", "reputational/legal complaint → CEO", "accumulating technical dissatisfaction → CTO", "mass outage signs → NOC + CTO"], ["calls", "applications", "complaints"], ["service level", "monthly/quarterly report by the 5th"], ["S&O head", "CTO", "Sales", "Billing", "Marketing"], "office",
   note="Hiring/firing formalized only by CEO order (S02 3.1)."),
 R("3.2", "Զանգերի կենտրոնի ավագ օպերատոր", "FN-CS", "3.1", ["3.4 ×6"], 1, 0, "Կարող է սպասել", 0, "Shift quality: daily guidance, escalated calls, call listening, application completeness", ["redistribute shift load", "return incomplete application", "take over a call"], ["written complaint/compensation/reputation → 3.1", "SLA-risk technical application → 3.1", "repeated calls from one area (mass outage) → 3.1", "repeated discipline → 3.1"], [], ["weekly summary of repeat-call causes"], ["L2/field", "Sales", "Billing"], "office", note="Cannot approve tariff/discount/benefit."),
 R("3.3", "L & R մասնագետ", "FN-CS", "3.1", [], 1, 0, "Կարևոր", 0, "Reduce churn: find at-risk subscribers, contact cancellations same day, classify reason, retention offer within approved list; call QA",
   ["retention offer within approved benefits", "call sample selection", "reason classification"], ["retention condition outside approved list → 3.1", "technical-cause churn accumulation → 3.1 + CTO", "operator quality drop → 3.1", "mass cancellations from one area → 3.1"], ["at-risk lists", "cancellation requests", "call recordings"], ["retained subscribers", "monthly Retention & Quality report by the 5th"], ["Marketing (retention offers)", "Billing", "Technical"], "office",
   note="VACANT — the role that owns retention/churn in the JD does not exist yet (Conflict C02)."),
 R("3.4", "Զանգերի կենտրոնի օպերատոր", "FN-CS", "3.2", [], 6, 4, "Կարևոր", 0, "Inbound calls: identify in billing, L1 diagnosis, solve on first contact or register a complete application; up/cross-sell without pressure",
   ["L1 diagnosis steps within SOP", "application type/priority per classifier", "callback agreement within SLA"], ["conflict/complaint → 3.2", "non-standard → 3.2", "repeat call on open application → 3.2", "repeated calls from one area → 3.2", "cancellation statement → L&R specialist"], ["calls"], ["applications", "L1 resolutions"], ["L2/field", "Sales", "Billing"], "office", note="Cannot change or promise tariff/discount/benefit."),
 R("4.1", "Բիլինգի և եկամտի ղեկավար (+Համադրում/Աուդիտ)", "FN-BILL", "Վաճառքի և գործառնական ղեկավար (S01/S02) — roadmap says CEO/COO/CFO (C08)", ["4.2"], 1, 1, "Համալրված", 0,
   "Billing accuracy, revenue protection, collections, month-end closing/reconciliation, reporting & analytics (per JD; analytics scope disputed — C01)",
   ["approve/reject workflows within authority (discount, correction, reactivation exception, tariff change) per Approval Matrix", "suspend risky process pending clarification", "department priorities"], ["risky/financial/out-of-authority cases → CEO/COO/CFO level"], ["technical handoff", "payments", "sales tariff/discount data"], ["daily/weekly/monthly/quarterly billing reports", "reconciliation results", "write-off decisions"], ["Technical", "Sales", "Call center", "Finance"], "office",
   note="Approval Matrix thresholds are not defined anywhere (APPROVAL_RULE_UNKNOWN). BILL-01–BILL-37 process pack referenced but not in the workspace."),
 R("4.2", "Բիլինգի և եկամտի մասնագետ", "FN-BILL", "4.1", [], 1, 0, "Կրիտիկական", 0, "Daily billing operations: handoff check, account creation, tariff attach, invoices, payments, overdue control, suspension/restoration, collections tasking, PTP",
   ["operational billing/collections actions within SOP", "return incomplete technical handoff"], ["errors/exceptions/disputes → 4.1", "VIP/active-exception → 4.1", "broken promise → 4.1"], ["technical handoff", "bank statements", "overdue portfolio"], ["accounts, invoices, suspensions", "data for daily/weekly reports"], ["Technical", "Sales", "Call center", "Finance"], "office", note="VACANT — daily billing operations currently on the head (@P2, DERIVED)."),
 R("EXEC-CEO", "Գործադիր տնօրեն (CEO)", "FN-EXEC", "—", ["EXEC-CTO", "EXEC-SO", "ԱՁ contractors"], 1, "UNKNOWN", "n/a", "UNKNOWN", "Approves JD (S02), hiring/firing orders, contractors report to CEO", ["hiring/firing orders", "JD approval"], [], [], [], [], "office", conf="DERIVED", src=("S01", "S02"), note="Person UNKNOWN. Whether @P1 is the CEO is UNVERIFIED (Open-questions #11)."),
 R("EXEC-CTO", "Տեխնիկական բաժնի ղեկավար (CTO)", "FN-EXEC", "CEO (DERIVED)", ["2.1", "2.3", "2.6", "2.11", "2.12", "2.13", "2.14"], 1, "UNKNOWN", "n/a", "UNKNOWN", "Owns technical function; receives all dispatcher escalations while dispatcher is absent; approves RCAs", ["RCA approval", "materials/permits", "device mismatch decisions"], [], [], [], [], "mixed", conf="DERIVED", src=("S02",), note="Person UNKNOWN."),
 R("EXEC-SO", "Վաճառքի և գործառնական ղեկավար (Head of Sales & Operations)", "FN-EXEC", "CEO / @P1 (DERIVED)", ["1.1", "1.7", "3.1", "4.1"], 1, 1, "Համալրված", 0, "Owns Sales, Marketing, Customer service and Billing; annual sales plan approval; pricing escalation point; JD owner",
   ["annual plan approval (JD 1.1: 'Օպերացիոն ղեկավարի կողմից հաստատված')", "pricing/tariff escalation point for Sales head", "cadre decisions with Sales head"], ["strategy/staffing/budget → @P1 (green light)"], [], [], [], "office", conf="CONFIRMED", src=("S01", "S02", "S15"), note="= Gev (Deputy's owner)."),
 R("CTR-REC", "Հավաքագրման մասնագետ (ԱՁ)", "FN-EXEC", "Գործադիր տնօրեն", [], 1, 0, "Կարևոր", 0, "Recruiting (contractor, invoice-based)", [], [], [], [], [], "contract", note="Vacant — Sales head runs recruiting (S03). No JD card (S14)."),
 R("CTR-LAW", "Իրավաբան (ԱՁ)", "FN-EXEC", "Գործադիր տնօրեն", [], 1, 0, "Կարևոր", 0, "Legal (contractor)", [], [], [], [], [], "contract", note="No JD card (S14)."),
]

PRINCIPALS = [   # people appear in the core ONLY as tokens; token → name and role assignments live in overlay/ov_people.py
 {"id": "@P0", "org_relation": "workspace owner; Վաճառքի և գործառնական ղեկավար (EXEC-SO)", "conf": "CONFIRMED", "src": ["S15", "S01"]},
 {"id": "@P1", "org_relation": "approves the staffing plan, assigns Gev's tasks, demands the sales strategy, produces the churn prediction — organizational role UNVERIFIED (Open-questions #11)", "conf": "UNVERIFIED", "src": ["S07", "S10"]},
 {"id": "@P2", "org_relation": "performs billing head work (4.1) — DERIVED", "conf": "DERIVED", "src": ["S04", "S07", "S09"]},
 {"id": "@P3", "org_relation": "sales (strategy input, retention flow candidate) — role UNVERIFIED", "conf": "DERIVED", "src": ["S07", "S08", "S09"]},
 {"id": "@P4", "org_relation": "development (KPI logic, portal) — not in the staffing table", "conf": "DERIVED", "src": ["S07"]},
 {"id": "@P5", "org_relation": "customer service / retention operations — role UNVERIFIED", "conf": "DERIVED", "src": ["S08", "S09"]},
 {"id": "@P6", "org_relation": "former retention flow owner", "conf": "UNKNOWN", "src": ["S08"]},
 {"id": "@P7", "org_relation": "mentioned re: activity-drop analysis", "conf": "UNKNOWN", "src": ["S07"]},
 {"id": "@P8", "org_relation": "mentioned once", "conf": "UNKNOWN", "src": ["S07"]},
]

SYSTEMS = [
 {"id": "SYS-MB", "name": "MikroBill", "purpose": "Billing execution: subscriber accounts, tariffs, invoices, payments, suspension/restoration, statuses", "owner": "Բիլինգի և եկամտի ղեկավար (role) — person DERIVED @P2", "data": ["subscriber accounts & 8 statuses (pending confirmation)", "tariffs", "payments", "overdue/days", "CPE bindings"], "workflows": ["P-BILL-01..06", "P-RET-01 (benefits recorded)", "P-OPS-05 (CPE binding)"], "deps": ["Portal", "Bitrix24"], "src": ["S04", "S07"], "conf": "CONFIRMED", "deputy_access": "NONE (Open-questions #7)"},
 {"id": "SYS-B24", "name": "Bitrix24", "purpose": "CRM + tasks: deals, applications, task orchestration; planned approval workflows (discount/correction/reactivation/PTP)", "owner": "UNKNOWN (Bitrix24 admin referenced in roadmap)", "data": ["deals (mandatory: address, tariff, activation date — S03)", "applications", "tasks (the real tasks live here — not in Tasks.xlsx)"], "workflows": ["P-SALES-01..04", "P-OPS-01..02", "P-CS-01..02", "P-BILL-03/04 (planned)"], "deps": ["MikroBill", "Portal"], "src": ["S03", "S04", "S07", "S14"], "conf": "CONFIRMED", "deputy_access": "NONE"},
 {"id": "SYS-PORTAL", "name": "HouseNet Portal", "purpose": "Integration bridge across products; future rule/event orchestration; CRM-resident AI demo deployed", "owner": "@P4 (DERIVED) / @P1's team", "data": ["subscriber reference", "events"], "workflows": ["integration layer (roadmap WS7)"], "deps": ["MikroBill", "Bitrix24", "Network data"], "src": ["S04", "S07"], "conf": "DERIVED", "deputy_access": "NONE"},
 {"id": "SYS-PBX", "name": "PBX (call recording, call accounting)", "purpose": "Telesales & call-center call metrics (calls/day, conversion, service level, FCR, missed calls)", "owner": "UNKNOWN", "data": ["call logs/recordings"], "workflows": ["P-SALES-03", "P-CS-01"], "deps": [], "src": ["S01", "S03"], "conf": "CONFIRMED", "deputy_access": "NONE"},
 {"id": "SYS-NET", "name": "Network data (OLT/ONT, NetXMS/Zabbix monitoring, outages)", "purpose": "Uptime, incidents, outage-in-area churn signal, traffic signals", "owner": "NOC specialist (2.13) → CTO", "data": ["outages by town/PON", "traffic"], "workflows": ["P-OPS-03", "churn model signals"], "deps": [], "src": ["S02", "S04", "S06"], "conf": "CONFIRMED", "deputy_access": "NONE"},
 {"id": "SYS-CHURN", "name": "Churn prediction (rule-based scoring, @P1's team)", "purpose": "Weekly save-list generation from 12 weighted signals", "owner": "@P1 (deploy pending, no date)", "data": ["scores, bands, drivers per subscriber"], "workflows": ["P-RET-01"], "deps": ["MikroBill", "Network data"], "src": ["S05", "S06", "S08"], "conf": "CONFIRMED", "deputy_access": "file export only (S05)"},
 {"id": "SYS-CC", "name": "Command-center (Tasks.xlsx, Journal, this model)", "purpose": "Deputy's operating memory and task register", "owner": "Gev / Deputy", "data": ["tasks", "decisions", "commitments"], "workflows": ["P-MGMT-01"], "deps": [], "src": ["S09", "S15"], "conf": "CONFIRMED", "deputy_access": "FULL"},
]

SALES_MODEL = {
 "channels": F(["branch offices ×3", "telesales", "D2D", "marketing leads", "call-center inbound up-sell", "corporate (GAP)"], ["S01", "S02", "S03"]),
 "lead_sources": F(["provided call base (≥1,500 numbers for 2 telesales agents)", "sector address lists (D2D)", "paid ads / SMM", "inbound calls", "referrals in dense buildings ('8 connected → the 9th applies itself')"], ["S02", "S03"]),
 "lead_handling": F("Marketing → Sales/Call center handoff with a Lead Response SLA (value UNKNOWN); CRM deal mandatory fields: address, tariff, activation date", ["S02", "S03"]),
 "qualification": F("D2D agent qualifies against defined criteria and passes only complete applications; telesales/office discover need within approved tariffs", "S02"),
 "offer": F("Approved tariffs/promos only; 7,000 AMD is the floor — no discounting (strategy); value = connection in 24h, same-day repair by local tech, fixed price 12 months", ["S02", "S03"], "DERIVED", "24h/12-month promises are strategy proposal text, not an approved policy"),
 "sale_definition": F("A sale counts only when the deal is ACTIVATED (S01 KPI sheet)", "S01"),
 "activation_handoff": F("Sales application → installation task (dispatcher/CTO) → install per SLA → technical handoff → billing account + tariff (BILL-03/04/05) → active", ["S02"]),
 "lost_sale_handling": UNKNOWN("No lost-sale process in sources (lost_opportunity_analysis skill is L0)", ["S02"]),
 "upsell_cross_sell": F("Call-center operators offer other services without pressure; senior office specialist KPI 'փաթեթի բարձրացումների քանակ (upsell)'", ["S01", "S02"]),
 "retention": F("See P-RET-01; ownership disputed (C02); tracking system undefined (C03/GAP)", ["S02", "S08"], "DERIVED"),
 "targets": F("see targets.json (TG-NEW-BASELINE, TG-NEW-PHASE1, TG-D2D-PKG, TG-TELE-PKG, TG-PENETRATION) — PROPOSED unless APPROVED; MRR/cost projections are CONFIDENTIAL (overlay CV-07/CV-08)", "S03", "UNVERIFIED", "official annual sales plan is not in the workspace (TARGET_UNKNOWN)"),
 "team_responsibilities": F("Sales head splits the approved annual plan monthly by office/channel; senior specialists own office + personal sales; telesales senior owns base processing; D2D agents own sectors", "S02"),
 "management_rhythm": F(["daily scoreboard + weekly cut + deviation correction from day 14 (strategy)", "Thursday meeting only on sales stimulation (@P1 09-09)", "corporate monthly report: seen · talked · offered · signed (requested, undefined owner)"], ["S03", "S08", "S11"], "DERIVED"),
}

OPERATIONS_MODEL = {
 "incoming_work": F(["new-connection applications (Sales)", "fault applications (Call center L1 → L2 → field)", "NOC incidents", "network build program", "collections tasks (Billing → Call center)"], "S02"),
 "work_assignment": F("Dispatcher/system assigns field tasks; the dispatcher position does not exist in the staffing table — every JD escalation says 'մինչև հաստիքի համալրումը՝ CTO-ին' (C09)", ["S01", "S02"], "CONFIRMED"),
 "execution": F("Installation per checklist; in-home repair per Repair SOP; CRM closure with serial/mac/measurement/customer confirmation; CPE returns to provisioning", "S02"),
 "sla_deadline_logic": F({"new_connection_sla": "UNKNOWN value (strategy stop-rule: activation >5 days freezes new-sales plan; promise 24h)", "in_home_repair_sla": "UNKNOWN value", "line_fault_restoration_sla": "UNKNOWN value", "incident_classification": "≤5 min (NOC JD)", "line_fault_alert_escalation": "≤15 min", "complaint_resolution": "days — target UNKNOWN", "reactivation_sla": "defined as KPI, value UNKNOWN"}, ["S02", "S03", "S04"], "CONFIRMED"),
 "handoffs": F(["Sales → Installation (application accuracy & lead time)", "Installation → Billing (technical handoff BILL-03)", "Call center L1 → L2 → field", "Field → Provisioning (CPE returns)", "NOC → CTO + Call center (mass outage)"], "S02"),
 "capacity": F("Installation calendar minimum 4 slots/day (strategy prerequisite); 13 of 22 technical positions filled; installation head & 3 senior installers vacant", ["S01", "S03"]),
 "backlog": UNKNOWN("No backlog/queue data in the workspace; ops_data must be supplied (CRM export)", ["S02"]),
 "failures_rework": F("Repeat visits / repeat applications are KPIs (share of repeats, first-visit resolution); RCA by group heads with CTO approval; ≤0.05 dB splice acceptance", ["S01", "S02"]),
 "escalations": F("Ladder in every JD card: specialist → senior/group head → CTO; mass outage → NOC → CTO + Call center; reputational/legal complaint → CEO", "S02"),
 "customer_incidents": F("NOC classifies ≤5 min by level/area, informs CTO and Call center; repeated calls from one area = mass-outage signal escalated by operators", "S02"),
 "completion_criteria": F("Application closed in CRM with measurements, serial/mac, materials and subscriber confirmation; incident closed after monitoring confirms restoration", "S02"),
}

PEOPLE_MODEL = {
 "staffing_structure": F("4 divisions · 29 position types · 52 positions (25 filled) + 2 contractors + 3 execs = 57; vacancy priority Կրիտիկական 13 / Կարևոր 6 / Կարող է սպասել 8", "S01"),
 "role_definitions": F("JD v1.1 cards (purpose, functions, decision rights, escalation, interaction, evaluation directions, qualification) — pending each head's OK", "S02"),
 "performance_expectations": F("Model Ա: fix + KPI bonus by weighted KPI attainment — <80%: 0 · 80–89%: +15% · 90–99%: +25% · 100–119%: +35% · ≥120%: +50%; Model Բ (D2D): fix only ≥80% of plan + 100% of sold tariffs, no ceiling; Model Գ contractors: invoice only. Probation 3 months: month 1 fix 80%/bonus 0; months 2–3 fix 100%/bonus 50%; month 4+ full", "S01"),
 "workload_capacity": F("KPI 'խմբի հաստիքների զբաղվածություն' exists for in-home head; no capacity model in sources", ["S01"], "DERIVED"),
 "performance_review_logic": F("Monthly KPI attainment → bonus tier; JD evaluation directions per role (no numbers in JD); numeric targets per KPI are NOT defined (TARGET_UNKNOWN)", ["S01", "S02"]),
 "training_coaching": F("Group heads/seniors train juniors (Skills Matrix, onboarding checklists); telesales senior trains on tariffs/objections/contract before field day 13 (strategy)", ["S02", "S03"]),
 "escalation_rules": F("Discipline: repeated issues → group head → department head; hiring/firing only by CEO order; performance stop-rules for new sales hires (S03 proposal): month-1 D2D <5 / telesales <10 → contract ends; 2 months <80% → termination; branch 2 months below baseline → head review", ["S02", "S03"], "DERIVED"),
}

CONFLICTS = [
 {"id": "C01", "topic": "Who owns analytics/BI (dashboards, forecast, churn scoring)", "source_a": "S04 Billing roadmap: Billing Department mandate includes 'Reporting & intelligence' + predictive analytics (churn score, forecast)", "source_b": "S11/S07 Gev's position 2026-09-09: BI/analytics OFF billing; MikroBill = source of truth only; KPIs not static", "newer": "S11 (2026-09-09)", "apparent_authority": "S04 is @P1-sent roadmap (v2); Gev's amendment sent, @P1's acceptance NOT recorded", "business_impact": "Ownership of Weekly Churn Risk Report, Monthly Revenue Forecast, KPI dictionary review cadence; roadmap workstreams 5–6", "resolution_required": "@P1 confirms or rejects the two amendments (Tasks.xlsx #5)", "status": "OPEN"},
 {"id": "C02", "topic": "Who owns retention / churn calls", "source_a": "S02 JD: L & R մասնագետ (3.3, vacant) + Հաճախորդների սպասարկման ղեկավար (3.1) own retention", "source_b": "S08 @P1 09-09 12:36: close the retention flow on @P3; Gev 12:41–12:44: calls go to telesales (tele senior) reporting to @P5 until a retention specialist exists", "newer": "S08 (2026-09-09)", "apparent_authority": "JD is the structural truth (draft-final); the chat is the operating decision of the moment", "business_impact": "Save-list (30 subscribers) has no single accountable owner; retention report line undefined", "resolution_required": "Gev to fix one accountable owner (role + person) and reflect it in the strategy doc (Tasks #12/#13)", "status": "OPEN"},
 {"id": "C03", "topic": "Churn-call tracking mechanism", "source_a": "@P1 (S08): each churn call should become a Bitrix24 task (evidence EV-05)", "source_b": "Gev (S08): daily routine, not a task; tracking via telesales senior → @P5 (daily if red, weekly otherwise), Excel (evidence EV-06)", "newer": "same conversation 2026-09-09", "apparent_authority": "no decision recorded", "business_impact": "No system of record for retention outcomes → churn KPI unmeasurable", "resolution_required": "Decision + design of the retention tracking system (Tasks #13, due 09-11)", "status": "OPEN"},
 {"id": "C05", "topic": "D2D average package price assumption", "source_a": "S01 Model Բ parameter: average tariff per package 8,000 AMD", "source_b": "S03 strategy: 7,000 AMD dominant package; calculations at 7,000", "newer": "S03 (2026-09-09)", "apparent_authority": "S01 approved (Reference) vs S03 proposal", "business_impact": "D2D commission/earnings scenarios and MRR projections differ by ~14%", "resolution_required": "Align the D2D pay model parameter with the strategy price floor before hiring D2D agents", "status": "OPEN"},
 {"id": "C08", "topic": "Billing head reporting line", "source_a": "S01/S02: Բիլինգի և եկամտի ղեկավար → Վաճառքի և գործառնական ղեկավար", "source_b": "S04 roadmap: report line CEO (global), COO & CFO (ongoing control)", "newer": "S02 (2026-09-05) vs roadmap dated 2026-03-17 (sent 09-07)", "apparent_authority": "S01 approved staffing wins structurally; roadmap describes a target model with COO/CFO that do not exist in the staffing table", "business_impact": "Escalation path for billing exceptions/approvals is ambiguous; 'COO/CFO' approvers undefined", "resolution_required": "Confirm that S&O head = escalation/approval point for billing until COO/CFO roles exist", "status": "OPEN"},
 {"id": "C09", "topic": "Dispatcher role", "source_a": "S02 JD: 'Դիսպետչեր' assigns field tasks and receives SLA-risk escalations (with 'մինչև հաստիքի համալրումը՝ CTO-ին')", "source_b": "S01 staffing table: no dispatcher position exists", "newer": "S01 approved 2026-09-07", "apparent_authority": "S01", "business_impact": "Field task assignment and SLA-risk escalations all land on the CTO; no queue owner for installations/repairs", "resolution_required": "Decide: add a dispatcher position or assign the function to an existing role", "status": "OPEN"},
 {"id": "C10", "topic": "Role naming inside JD technical cards", "source_a": "S02 cards 2.7–2.10 refer to 'Ավագ գծային ճարտարագետ', 'Գծային ճարտարագետ', 'Զոդող-մալուխագործ, առաջատար մասնագետ'", "source_b": "S01/S02 titles: Լարանցման ավագ մասնագետ, Լարանցման մասնագետ, Եռակցման ավագ մասնագետ", "newer": "same document", "apparent_authority": "titles in the card headers", "business_impact": "Escalation targets are ambiguous inside the technical function", "resolution_required": "Editorial fix in JD v1.2 (Actions.md 'Ղեկավարների շղթա' check)", "status": "OPEN"},
]

# Facts Deputy must never state as confirmed
CRITICAL_UNKNOWNS = [
 {"id": "U01", "item": "'4 ամսվա մեջ ամսական 2% իջնելը' — WHAT metric declines 2%/month (active subscribers? revenue?)", "why_critical": "@P1 called it THE business-critical ask; Tasks #7 (@P2 → Գև) — no answer", "src": ["S07", "S09", "S10"]},
 {"id": "U02", "item": "Content of voice messages: Revenue Assurance TA (09-07 20:14/20:16)", "src": ["S07", "S10"]},
 {"id": "U03", "item": "Whether the staffing plan takes effect 2026-10-01", "src": ["S10"]},
 {"id": "U04", "item": "Which systems Deputy can access (MikroBill, Bitrix24, Portal, CRM) — currently none", "src": ["S10"]},
 {"id": "U05", "item": "Roles of @P1, @P2, @P3, @P4, @P5, @P6, @P7; who is the telesales senior", "src": ["S10"]},
 {"id": "U06", "item": "Official annual sales plan and per-KPI numeric targets", "src": ["S01", "S02"]},
 {"id": "U07", "item": "Approval thresholds (discount/correction/exception) — Approval Matrix", "src": ["S04", "S02"]},
 {"id": "U08", "item": "Confirmation of the 8 MikroBill subscriber statuses by @P1 (due 09-10)", "src": ["S07", "S11"]},
 {"id": "U09", "item": "Bitrix24 tasks that are not in Tasks.xlsx (register incomplete)", "src": ["S14", "S10"]},
]
