# -*- coding: utf-8 -*-
"""KPI CATALOG — OUTCOME / DRIVER / OPERATIONAL. Targets, thresholds and formulas are UNKNOWN unless a source states them.
ROLE_KPIS = the approved per-role KPI weights (S01 KPI sheet): weights are CONFIRMED, targets are not."""

def K(kid, name, kind, definition, purpose, formula, unit, source_system, owner, freq, target, warn, crit, dims, drivers, outcomes, action, src, conf="CONFIRMED", note=None):
    d = {"kpi_id": kid, "name": name, "kind": kind, "definition": definition, "business_purpose": purpose, "formula": formula, "unit": unit, "source": source_system, "owner": owner,
         "reporting_frequency": freq, "target": target, "warning_threshold": warn, "critical_threshold": crit, "drill_down": dims, "driver_kpis": drivers, "outcome_kpis": outcomes,
         "action_when_off_target": action, "src": list(src), "conf": conf}
    if note: d["note"] = note
    return d

U = "UNKNOWN"
KPIS = [
 K("K-ACT", "Active subscribers", "OUTCOME", "Subscribers with status Ակտիվ (Days ≥ 0) in MikroBill", "The base that pays; density on the built network", "count(status=Active)", "subscribers", "SYS-MB", "Վաճառքի և գործառնական ղեկավար (DERIVED)", "daily/monthly", U, U, U, ["branch", "tariff", "agreement type", "area/PON"], ["K-NEW", "K-CHURN", "K-REACT"], [], "Playbook PB-01/PB-05; investigate the '±300 active' anomaly (U01)", ["S07", "S04"], "DERIVED", "@P1: 'ակտիվների քանակը իջնում ա 300-ով, հետո հելնում' — unexplained; the '2%/month over 4 months' metric may be this (U01)"),
 K("K-NEW", "New activations per month", "OUTCOME", "Activated deals (sale = activated only) per month by branch/channel", "Growth; plan attainment", "count(activations in month)", "activations", "SYS-MB (KPI source 'Բիլինգ')", "Վաճառքի ղեկավար (1.1)", "daily scoreboard / weekly / monthly", "see targets.json TG-NEW-BASELINE / TG-NEW-PHASE1 (PROPOSED); official annual plan UNKNOWN", "UNKNOWN", "TG-STOP-2M (PROPOSED)", ["branch", "channel (office/telesales/D2D/marketing)", "agent", "tariff"], ["K-D2D-PKG", "K-TELE-PKG", "K-LEADS", "K-ACTIVATION-DAYS"], ["K-ACT", "K-MRR-NEW"], "PB-01 Sales decline / PB-02 Missed target", ["S01", "S03"], "CONFIRMED", "targets referenced by id from targets.json"),
 K("K-MRR-NEW", "New MRR", "OUTCOME", "Monthly recurring revenue added by new activations", "Revenue growth", "Σ activations × package price", "AMD/month", "SYS-MB", "Վաճառքի ղեկավար (1.1)", "monthly", "CONFIDENTIAL — overlay CV-07/CV-08", U, U, ["branch", "package"], ["K-NEW", "K-ARPU"], [], "PB-01/PB-02", ["S03"], "UNVERIFIED"),
 K("K-ARPU", "Average package price (ARPU proxy)", "DRIVER", "Average monthly fee of the sales mix", "Price floor policy 7,000; mix of Lite/iPlus lowers it", "Σ fees / subscribers", "AMD", "SYS-MB", "Վաճառքի ղեկավար (1.1)", "monthly", "see targets.json TG-DISCOUNT-FLOOR (PROPOSED); C05 (Model Բ parameter differs)", U, U, ["tariff", "branch"], [], ["K-MRR-NEW"], "Flag mix shift; never discount (strategy)", ["S01", "S03"], "DERIVED"),
 K("K-CHURN", "Churn rate", "OUTCOME", "Share of active subscribers lost (cancelled/abandoned) per month — exact status set pending (S18)", "Retention; the base erodes if churn > growth", "lost / active_start", "%", "SYS-MB", "CONFLICT C02 (JD: L&R 3.3 / CS head 3.1)", "weekly (roadmap) / monthly", U, U, U, ["reason class (technical/price/service/external)", "area", "tariff", "agreement type", "tenure"], ["K-CHURN-RISK", "K-COMPLAINTS", "K-OUTAGES"], ["K-ACT"], "PB-05 Churn increase; P-RET-01", ["S01", "S02", "S04", "S06"], "CONFIRMED", "'Churn % նորմայի մեջ' is an L&R KPI — the norm is UNKNOWN"),
 K("K-CHURN-RISK", "Churn-risk save list", "DRIVER", "Subscribers with score ≥70, ≥3 hot signals, coverage ≥60% (rule model, 12 weighted signals)", "Proactive retention calling", "weighted rule score (Irregular payment 18 · Days since last payment 12 · No yearly agreement 12 · Outages in area 10 · Traffic falling 9 · Agreement ending 8 · Tenure 8 · Payments this year 7 · Paying not using 6 · Switched off by operator 5 · Temporary pause 3 · Cheaper tariff 2)", "subscribers", "SYS-CHURN", "@P1 (model); callers @P5 + @P2 (C02)", "weekly", U, U, U, ["band SEVERE/HIGH", "area", "drivers"], [], ["K-CHURN", "K-RETAINED"], "Work the list same week; add complaint-calls signal (Gev)", ["S05", "S06"], "CONFIRMED", "Rank, not probability — uncalibrated. Subscriber-derived aggregates: overlay EV-01"),
 K("K-RETAINED", "Retained subscribers", "OUTCOME", "At-risk/cancelling subscribers kept active after retention contact", "Retention effectiveness", "kept / contacted", "count, %", "SYS-MB + tracking system (GAP)", "L&R specialist (3.3, vacant) — C02", "monthly report by the 5th", U, U, U, ["reason class", "offer used"], ["K-CHURN-RISK"], ["K-CHURN"], "PB-05; fix tracking (P-MGMT-05)", ["S01", "S02"], "CONFIRMED"),
 K("K-PENETRATION", "Sector penetration", "DRIVER", "Active subscribers ÷ covered apartments in a sector", "Density strategy: no second sector before 40%", "active / covered", "%", "SYS-MB + coverage map", "Վաճառքի ղեկավար (1.1)", "monthly", "TG-PENETRATION (PROPOSED)", U, U, ["sector", "building"], ["K-D2D-PKG"], ["K-ACT"], "Keep agents in the sector", ["S03"], "UNVERIFIED"),
 K("K-D2D-PKG", "D2D packages per agent", "DRIVER", "Activated packages sold by a D2D agent per month", "Pay model Բ threshold and stop rules", "count", "packages", "SYS-MB", "Վաճառքի ղեկավար (1.1)", "daily/monthly", "TG-D2D-PKG", "TG-D2D-FIX-THRESHOLD", "TG-STOP-D2D-M1 (PROPOSED)", ["agent", "sector"], [], ["K-NEW"], "PB-02", ["S01", "S03"]),
 K("K-TELE-PKG", "Telesales packages per agent", "DRIVER", "Activated telesales per agent per month", "Telesales productivity", "count", "packages", "SYS-MB", "Հեռախոսային վաճառքի ավագ մասնագետ (1.4)", "daily/monthly", "TG-TELE-PKG (PROPOSED)", U, "TG-STOP-TELE-M1 (PROPOSED)", ["agent"], ["K-CALLS-DAY", "K-CALL-CONV"], ["K-NEW"], "PB-02/PB-04", ["S03"], "UNVERIFIED"),
 K("K-CALLS-DAY", "Calls per day vs norm", "OPERATIONAL", "Outbound calls per telesales agent vs daily norm", "Activity driver", "calls / norm", "%", "SYS-PBX", "1.4", "daily", U, U, U, ["agent"], [], ["K-TELE-PKG"], "Coaching; base quality check", ["S01"]),
 K("K-CALL-CONV", "Call → sale conversion", "DRIVER", "Sales ÷ calls (telesales); meeting → sale (office)", "Conversion health", "sales / calls", "%", "SYS-PBX + SYS-MB", "1.4 / 1.2", "weekly", U, U, U, ["agent", "script", "base source"], ["K-CALLS-DAY"], ["K-NEW"], "PB-04 Conversion deterioration", ["S01"]),
 K("K-LEADS", "Marketing leads & conversion", "DRIVER", "Leads by source; lead → sale conversion; CPL", "Acquisition funnel", "leads; sales/leads; spend/leads", "count, %, AMD", "SYS-B24 + Ads", "Մարքեթինգի ղեկավար (1.7)", "weekly/monthly", U, U, U, ["source", "campaign"], [], ["K-NEW"], "PB-04", ["S01", "S02"]),
 K("K-ACTIVATION-DAYS", "Activation lead time", "OPERATIONAL", "Days from sale/application to activation", "Promise '24h'; capacity gate", "activation_date − sale_date", "days", "SYS-B24/SYS-MB", "Տեղադրման խմբի ղեկավար (2.3, vacant → CTO)", "daily", "TG-SLA-INSTALL (UNKNOWN); promise TG-SLA-ACTIVATION-PROMISE (PROPOSED)", U, "TG-SLA-ACTIVATION-FREEZE (PROPOSED)", ["branch", "installer"], ["K-INSTALL-CAP"], ["K-NEW"], "PB-07/PB-08", ["S01", "S02", "S03"], "CONFIRMED"),
 K("K-INSTALL-CAP", "Installation capacity", "OPERATIONAL", "Available install slots per day", "Sales cannot exceed install capacity", "slots/day", "slots", "SYS-B24", "2.3 (vacant → CTO)", "daily", "UNKNOWN (strategy prerequisite ≥4 slots/day — PROPOSED, not a target entry)", U, U, ["day", "team"], [], ["K-ACTIVATION-DAYS"], "PB-14 Capacity shortage", ["S03"], "UNVERIFIED"),
 K("K-REPEAT", "Repeat visits / repeat applications share", "OPERATIONAL", "Share of installations/repairs needing a second visit or repeat application (≤30 days)", "Rework and quality", "repeats / total", "%", "SYS-B24", "2.1 / 2.3", "weekly", U, U, U, ["team", "engineer", "cause"], [], ["K-CHURN", "K-COMPLAINTS"], "PB-15 Repeated operational failure; RCA", ["S01", "S02"]),
 K("K-SLA-INHOME", "In-home repair SLA attainment", "OPERATIONAL", "Repairs closed within the in-home SLA", "Service quality", "in_sla / total", "%", "SYS-B24", "2.1", "weekly", U, U, U, ["team"], [], ["K-CHURN"], "PB-08 SLA deterioration", ["S01", "S02"], "CONFIRMED", "SLA value itself UNKNOWN"),
 K("K-UPTIME", "Network availability (uptime)", "OPERATIONAL", "Network/service availability from monitoring", "Outages drive churn (signal weight 10)", "up_time / total", "%", "SYS-NET", "2.13 → CTO", "daily", U, U, U, ["town", "PON"], ["K-INCIDENT-DETECT"], ["K-CHURN"], "PB-15", ["S01", "S02", "S06"]),
 K("K-INCIDENT-DETECT", "Incident detection/classification time", "OPERATIONAL", "Alert → classified incident", "Fast escalation", "minutes", "min", "SYS-NET", "2.13", "per incident", "TG-SLA-INCIDENT-CLASSIFY / TG-SLA-LINE-ESCALATION (PROPOSED — JD unsigned)", U, U, ["level"], [], ["K-UPTIME"], "P-OPS-03", ["S02"]),
 K("K-SERVICE-LEVEL", "Call-center service level / answer time", "OPERATIONAL", "Calls answered within threshold; missed calls", "First contact quality", "answered_in_x / offered", "%", "SYS-PBX", "3.1", "daily", U, U, U, ["shift", "operator"], [], ["K-COMPLAINTS"], "PB-14", ["S01", "S02"]),
 K("K-FCR", "First-contact resolution", "OPERATIONAL", "Calls solved without application/repeat", "Efficiency & satisfaction", "fcr / calls", "%", "SYS-PBX/SYS-B24", "3.2 (vacant → 3.1)", "weekly", U, U, U, ["operator"], [], ["K-COMPLAINTS"], "Training via 3.3 QA", ["S01"]),
 K("K-COMPLAINTS", "Complaints: count & resolution days", "OUTCOME", "Registered complaints and days to resolve", "Customer experience; churn driver", "count; avg days", "count, days", "SYS-B24", "3.1", "weekly/monthly (report by the 5th)", U, U, U, ["type", "area", "cause"], ["K-REPEAT", "K-SLA-INHOME"], ["K-CHURN"], "PB-09 Repeated complaints", ["S01", "S02"]),
 K("K-COLLECT", "Revenue collection level", "OUTCOME", "Collected ÷ billed", "Cash; revenue protection", "collected / billed", "%", "SYS-MB", "Բիլինգի և եկամտի ղեկավար (4.1)", "daily/monthly", U, U, U, ["channel", "segment", "branch"], ["K-OVERDUE", "K-RECOVERY"], [], "PB-06 Revenue leakage suspicion", ["S01", "S04"]),
 K("K-OVERDUE", "Overdue portfolio (buckets)", "DRIVER", "Overdue balance by aging bucket", "Debt control", "Σ overdue by bucket", "AMD", "SYS-MB", "4.1", "daily/weekly/monthly", U, U, U, ["bucket", "segment", "VIP/exception"], [], ["K-COLLECT"], "P-BILL-03; weekly debt report (roadmap)", ["S04"]),
 K("K-RECOVERY", "Recovery rate", "DRIVER", "Recovered ÷ overdue in bucket", "Collections effectiveness", "recovered / overdue", "%", "SYS-MB", "4.1", "weekly/monthly", U, U, U, ["bucket", "caller"], ["K-PTP"], ["K-COLLECT"], "PB-06", ["S01", "S04"]),
 K("K-PTP", "Promise-to-pay kept rate", "OPERATIONAL", "PTP kept ÷ PTP made", "Collections discipline", "kept / made", "%", "SYS-B24 (planned)", "4.2 (vacant → 4.1)", "weekly", U, U, U, ["caller"], [], ["K-RECOVERY"], "Broken promise → 4.1", ["S02", "S04"], "CONFIRMED", "Tracking not live (roadmap Q2)"),
 K("K-BILL-ACC", "Billing accuracy rate", "OUTCOME", "Share of correct invoices/charges; manual errors", "Trust & revenue", "correct / total", "%", "SYS-MB", "4.1", "weekly/monthly", U, U, U, ["error type"], [], ["K-COLLECT", "K-COMPLAINTS"], "PB-06", ["S01", "S04"]),
 K("K-LEAK", "Revenue leakage cases", "OUTCOME", "Unbilled active, billed inactive, wrong tariff, unauthorized discount, correction anomalies", "Revenue protection (COO/CFO primary control)", "count; estimated AMD", "cases, AMD", "SYS-MB + SYS-PORTAL", "4.1", "weekly/monthly", U, U, U, ["type", "root cause"], ["K-BILL-ACC"], ["K-COLLECT"], "PB-06", ["S04"]),
 K("K-RECON", "Reconciliation mismatches & month-end closing days", "OPERATIONAL", "Mismatches between billing and payments; days to close", "Financial accuracy", "count; days", "count, days", "SYS-MB/Excel", "4.1", "monthly", U, U, U, ["mismatch type"], [], ["K-COLLECT"], "P-BILL-05", ["S01"]),
 K("K-TASK-OVERDUE", "Overdue management tasks", "OPERATIONAL", "Tasks.xlsx rows past deadline", "Management discipline (@P1 asks)", "count(deadline < today & open)", "tasks", "SYS-CC", "Deputy → Gev", "daily", 0, "1", "critical ask overdue", ["owner"], [], [], "PB-11 Important overdue task", ["S09", "S15"]),
 K("K-VACANCY", "Vacancy fill", "OPERATIONAL", "Filled ÷ positions; critical vacancies open", "Capacity", "filled / positions", "%", "S01", "Վաճառքի և գործառնական ղեկավար", "monthly", U, U, "13 critical vacant (2026-09-07)", ["division", "priority"], [], ["K-NEW", "K-INSTALL-CAP"], "PB-14", ["S01"]),
]

# Approved per-role KPI weights (S01 'KPI' sheet). ids R-<role>-<n>. Targets: NONE defined (TARGET_UNKNOWN).
_ROLE = {
 "1.1": [("Բաժնի վաճառքի պլանի կատարում", .40, "աճող", "%", "Բիլինգ"), ("Վաճառքի թիմի պլանի կատարում", .25, "աճող", "%", "CRM"), ("Հեռախոսային վաճառքի թիմի պլանի կատարում", .20, "աճող", "%", "CRM"), ("Մարքեթինգի լիդերի փոխարկում վաճառքի", .15, "աճող", "%", "CRM")],
 "1.2": [("Ավագի անձնական վաճառք (ակտիվացած)", .40, "աճող", "հատ", "Բիլինգ"), ("Ենթակա վաճառքի մասնագետների պլանի կատարում", .30, "աճող", "%", "CRM"), ("Փաթեթի բարձրացումների քանակ (upsell)", .15, "աճող", "հատ", "Բիլինգ"), ("CRM-ի գործարքների լրացվածություն", .15, "աճող", "%", "CRM")],
 "1.3": [("Մասնագետի անձնական վաճառք (ակտիվացած)", .65, "աճող", "հատ", "Բիլինգ"), ("Հանդիպում → վաճառք փոխարկում", .20, "աճող", "%", "CRM"), ("Գործարքի փաստաթղթային ճշտություն", .15, "աճող", "%", "CRM")],
 "1.4": [("Անձնական հեռավաճառք (ակտիվացած)", .35, "աճող", "հատ", "Բիլինգ"), ("Ենթակա գործակալների պլանի կատարում", .30, "աճող", "%", "CRM"), ("Խմբի զանգ → վաճառք փոխարկում", .20, "աճող", "%", "PBX"), ("Խմբի զանգերի նորմայի կատարում", .15, "աճող", "%", "PBX")],
 "1.5": [("Հեռավաճառք (ակտիվացած)", .60, "աճող", "հատ", "Բիլինգ"), ("Զանգ → վաճառք փոխարկում", .25, "աճող", "%", "PBX"), ("Օրական զանգերի նորմայի կատարում", .15, "աճող", "%", "PBX")],
 "1.6": [],
 "1.7": [("Մարքեթինգից եկած վաճառքի քանակ", .35, "աճող", "հատ", "CRM"), ("Լիդի արժեք (CPL) նորմայի մեջ", .25, "նվազող", "֏", "Ads"), ("Performance ուղղության պլանի կատարում", .20, "աճող", "%", "CRM"), ("SMM ուղղության պլանի կատարում", .20, "աճող", "%", "CRM")],
 "1.8": [("Վճարովի գովազդի լիդերի քանակ", .45, "աճող", "հատ", "CRM"), ("Վճարովի լիդի արժեք (CPL)", .30, "նվազող", "֏", "Ads"), ("Վճարովի լիդ → վաճառք փոխարկում", .25, "աճող", "%", "CRM")],
 "1.9": [("Բովանդակության պլանի կատարում", .40, "աճող", "%", "Excel"), ("Օրգանական հասման աճ", .30, "աճող", "%", "Meta"), ("Սոց. ցանցերից եկած լիդեր", .30, "աճող", "հատ", "CRM")],
 "2.1": [("Ներտնային հայտերի փակման պլան", .40, "աճող", "%", "CRM"), ("Ներտնային SLA-ի կատարում", .30, "աճող", "%", "CRM"), ("Կրկնվող հայտերի մասնաբաժին", .20, "նվազող", "%", "CRM"), ("Խմբի հաստիքների զբաղվածություն", .10, "աճող", "%", "Excel")],
 "2.2": [("Փակված ներտնային հայտեր", .55, "աճող", "հատ", "CRM"), ("Ներտնային SLA-ի մեջ լուծում", .30, "աճող", "%", "CRM"), ("Կրկնվող հայտի բացակայություն", .15, "աճող", "%", "CRM")],
 "2.3": [("Տեղադրումների պլանի կատարում", .40, "աճող", "%", "CRM"), ("Տեղադրման SLA", .30, "աճող", "%", "CRM"), ("Նոր վաճառքի ակտիվացման ժամկետ", .20, "նվազող", "օր", "CRM"), ("Նյութի ծախսի նորմայի պահպանում", .10, "աճող", "%", "Excel")],
 "2.4": [("Անձնական տեղադրումների քանակ", .35, "աճող", "հատ", "CRM"), ("Ենթակա տեղադրողների պլանի կատարում", .30, "աճող", "%", "CRM"), ("Տեղադրման SLA (խմբի)", .20, "աճող", "%", "CRM"), ("Կրկնակի այցի բացակայություն", .15, "աճող", "%", "CRM")],
 "2.5": [("Կատարված տեղադրումներ", .55, "աճող", "հատ", "CRM"), ("Տեղադրման ժամկետի պահպանում", .30, "աճող", "%", "CRM"), ("Կրկնակի այցի բացակայություն (անձնական)", .15, "աճող", "%", "CRM")],
 "2.6": [("Ցանցի կառուցման պլանի կատարում", .40, "աճող", "%", "Excel"), ("Լարանցման խմբի պլանի կատարում", .25, "աճող", "%", "Excel"), ("Եռակցման խմբի պլանի կատարում", .25, "աճող", "%", "Excel"), ("Կառուցման նյութի ծախս նորմայի մեջ", .10, "աճող", "%", "Excel")],
 "2.7": [("Անձնական լարանցման ծավալ", .35, "աճող", "մետր", "Excel"), ("Ենթակա լարանցողների պլանի կատարում", .30, "աճող", "%", "Excel"), ("Լարանցման ժամկետների պահպանում (խմբի)", .20, "աճող", "%", "Excel"), ("Վերալարանցման բացակայություն", .15, "աճող", "%", "Excel")],
 "2.8": [("Լարանցման ծավալ", .55, "աճող", "մետր", "Excel"), ("Լարանցման ժամկետի պահպանում", .30, "աճող", "%", "Excel"), ("Վերալարանցման բացակայություն (անձնական)", .15, "աճող", "%", "Excel")],
 "2.9": [("Անձնական եռակցումների քանակ", .35, "աճող", "հատ", "Excel"), ("Ենթակա եռակցողների պլանի կատարում", .30, "աճող", "%", "Excel"), ("Եռակցման կորուստը նորմայի մեջ (խմբի)", .20, "նվազող", "dB", "Մոնիտորինգ"), ("Կրկնակի եռակցման բացակայություն", .15, "աճող", "%", "Excel")],
 "2.10": [("Եռակցումների քանակ", .55, "աճող", "հատ", "Excel"), ("Եռակցման կորուստը նորմայի մեջ", .30, "նվազող", "dB", "Մոնիտորինգ"), ("Կրկնակի եռակցման բացակայություն (անձնական)", .15, "աճող", "%", "Excel")],
 "2.11": [("Կարգավորված սարքավորումների քանակ", .50, "աճող", "հատ", "CRM"), ("Կարգավորման ժամկետի պահպանում", .30, "աճող", "%", "CRM"), ("Սարքի խափանում կարգավորումից հետո", .20, "նվազող", "%", "CRM")],
 "2.12": [("Գույքագրման ճշտություն", .45, "աճող", "%", "Excel"), ("Պահեստի շարժի փաստաթղթավորման ժամկետ", .30, "նվազող", "օր", "Excel"), ("Նյութի պակասորդ", .25, "նվազող", "%", "Excel")],
 "2.13": [("Ցանցի հասանելիություն (uptime)", .40, "աճող", "%", "Մոնիտորինգ"), ("Ինցիդենտի հայտնաբերման ժամանակ", .30, "նվազող", "րոպե", "Մոնիտորինգ"), ("Backup-ի պլանի կատարում", .30, "աճող", "%", "Մոնիտորինգ")],
 "2.14": [("Լուծված L2 էսկալացիաներ", .45, "աճող", "հատ", "CRM"), ("L2 ինցիդենտի լուծման միջին ժամանակ", .35, "նվազող", "ժամ", "CRM"), ("Կրկնվող էսկալացիայի բացակայություն", .20, "աճող", "%", "CRM")],
 "3.1": [("Զանգերի կենտրոնի սպասարկման մակարդակ", .35, "աճող", "%", "PBX"), ("Բողոքների լուծման ժամկետ", .25, "նվազող", "օր", "CRM"), ("Հաճախորդների պահպանման մակարդակ", .25, "աճող", "%", "Բիլինգ"), ("Որակի ապահովման (ՈԱ) գնահատական", .15, "աճող", "%", "Excel")],
 "3.2": [("Ենթակա օպերատորների պլանի կատարում", .35, "աճող", "%", "PBX"), ("Անձնական սպասարկված զանգեր", .25, "աճող", "հատ", "PBX"), ("Առաջին կոնտակտով լուծում (FCR)", .20, "աճող", "%", "PBX"), ("Խմբի բաց թողած զանգեր", .20, "նվազող", "%", "PBX")],
 "3.3": [("Պահպանված հաճախորդների քանակ", .50, "աճող", "հատ", "Բիլինգ"), ("Churn % նորմայի մեջ", .30, "նվազող", "%", "Բիլինգ"), ("Վերադարձված (win-back) հաճախորդներ", .20, "աճող", "հատ", "Բիլինգ")],
 "3.4": [("Սպասարկված զանգերի քանակ", .40, "աճող", "հատ", "PBX"), ("Առաջին կոնտակտով լուծում (FCR, անձնական)", .30, "աճող", "%", "PBX"), ("Անձնական բաց թողած զանգեր", .30, "նվազող", "%", "PBX")],
 "4.1": [("Եկամտի հավաքագրման մակարդակ", .35, "աճող", "%", "Բիլինգ"), ("Հաշվարկների ճշտություն", .25, "աճող", "%", "Բիլինգ"), ("Ամսական փակման ժամկետ", .20, "նվազող", "օր", "Excel"), ("Համադրման անհամապատասխանություններ", .20, "նվազող", "հատ", "Excel")],
 "4.2": [("Ժամանակին դուրս գրված հաշիվներ", .40, "աճող", "%", "Բիլինգ"), ("Ժամկետանց պարտքի հավաքագրում", .40, "աճող", "%", "Բիլինգ"), ("Հաշվարկային սխալների քանակ", .20, "նվազող", "հատ", "Բիլինգ")],
}
ROLE_KPIS = {code: [{"kpi_id": f"R-{code}-{i+1}", "name": n, "weight": w, "direction": d, "unit": u, "source": s, "target": "UNKNOWN", "kind": "OPERATIONAL", "src": ["S01"], "conf": "CONFIRMED"} for i, (n, w, d, u, s) in enumerate(items)] for code, items in _ROLE.items()}
