# -*- coding: utf-8 -*-
"""MANAGEMENT PLAYBOOKS — executable context for recurring situations. Each ends SIGNAL → VERIFY → DIAGNOSE → ROOT CAUSE → IMPACT →
ACTION → OWNER → DEADLINE → FOLLOW-UP → VERIFY → CLOSE. `chain` links to the Skill System chain; `owner` cites the ownership map."""

FLOW = ["SIGNAL", "VERIFY", "DIAGNOSE", "ROOT CAUSE", "IMPACT", "ACTION", "OWNER", "DEADLINE", "FOLLOW-UP", "VERIFY", "CLOSE"]

def PB(pid, name, trigger, chain, skills, data, sources, diag, questions, impact, authority, esc, rec, fmt, owner, deadline, evidence, src, note=None):
    d = {"playbook_id": pid, "name": name, "trigger": trigger, "chain": chain, "required_skills": skills, "required_data": data, "required_sources": sources,
         "diagnostic_steps": diag, "questions_to_answer": questions, "business_impact": impact, "authority_boundary": authority, "escalation_threshold": esc,
         "expected_recommendation": rec, "action_format": fmt, "owner": owner, "deadline_logic": deadline, "completion_evidence": evidence, "flow": FLOW, "src": list(src)}
    if note: d["note"] = note
    return d

EXEC_FMT = "WHAT HAPPENED · WHY IT MATTERS · WHAT CAUSED IT · RECOMMENDATION · OWNER · BY WHEN · WHAT GEV MUST DO (charter §25/§27)"

PLAYBOOKS = [
 PB("PB-01", "Sales decline", "K-NEW / K-MRR-NEW below prior period or baseline; 'sales are down'", "investigate_sales_decline", ["sales_kpi_monitoring", "data_analysis", "root_cause_analysis", "decision_support"],
    ["activations by day/branch/channel/agent (MikroBill = 'Բիլինգ' KPI source)", "CRM deals by stage", "calls/day & conversion (PBX)", "install lead time & slots"], ["S01", "S03", "S09"],
    ["VERIFY the number against MikroBill activations (sale = activated only); exclude pending installs", "split by branch (19/18/18 baseline) and channel", "check activation lead time (installs pending > 5 days = sales stuck, not lost)", "check activity drivers: calls/day, visits, leads", "check vacancies: 3 sales specialists, 2 telesales, 6 D2D unfilled"],
    ["Is it fewer sales or slower activations?", "Which branch/channel/agent?", "Activity problem or conversion problem?", "Capacity (install slots) or demand?", "Did anything change: tariff, coverage, outage, competitor?"],
    "Base growth stalls; phase-1 payback (month 5/8) slips; density strategy fails", "Deputy: ANALYZE/RECOMMEND. Plan changes, pricing, hiring → Gev → @P1", "Branch 2 consecutive months below baseline → head review; any month < 80% of plan → P1 to Gev",
    "Named cause + one corrective action per branch/channel with owner and date; no discounting (strategy floor)", EXEC_FMT, "Վաճառքի ղեկավար (1.1) — person UNKNOWN", "Diagnosis within 2 working days; corrective action same week; re-check next weekly cut", "Activations recover to baseline in the next cut, evidenced by MikroBill count", ["S01", "S03", "S15"]),
 PB("PB-02", "Missed sales target", "Month closed below plan (official plan UNKNOWN — proposal 55/125)", "sales_target_missed", ["target_vs_actual", "sales_forecasting", "root_cause_analysis", "decision_support"],
    ["plan vs actual by branch/channel", "run-rate", "pipeline of pending installs"], ["S01", "S03"],
    ["confirm which plan (official annual plan is not in the workspace → TARGET_UNKNOWN unless supplied)", "gap by branch/channel/agent", "run-rate vs remaining days", "stop-rule check for new hires (S03)", "capacity vs demand"],
    ["How big is the gap and where?", "Structural (vacancies, coverage) or execution?", "Forecast for next month?", "Which stop rule applies?"],
    "Bonus tiers (Model Ա) and D2D fix threshold (80%) depend on plan attainment; payroll cost vs revenue", "RECOMMEND only; plan revision/terminations → Gev/CEO", "2 consecutive months < 80% → termination rule (proposal) — decision to Gev",
    "Gap closure plan per branch with owner; forecast; decision request if structural", EXEC_FMT, "Վաճառքի ղեկավար (1.1)", "Within 3 days of month close", "Next month attainment vs plan", ["S01", "S03"]),
 PB("PB-03", "Sales pipeline stagnation", "Deals not moving / stale CRM deals", "pipeline_stagnation", ["pipeline_management", "decision_support"],
    ["CRM deals with stage age, next action, owner (Bitrix24 export — Deputy has no access)"], ["S02", "S03"],
    ["list deals without next action/date", "pending installs vs sales (handoff stuck?)", "CRM completeness KPI (senior specialist 15% weight)", "mandatory fields present: address, tariff, activation date"],
    ["Stuck at offer, contract, install or activation?", "Whose deals?", "Data discipline or real stall?"],
    "Sales counted only on activation → stalled deals = zero revenue and wasted CAC", "RECOMMEND; reassignment → 1.1", "Deals older than activation SLA + 5 days → escalate to 1.1; pipeline_management skill is L0 → BLOCKED without sales_data",
    "Per-deal next action + owner; handoff fix if installs are the stall", EXEC_FMT, "Վաճառքի ղեկավար (1.1)", "Weekly cut", "Deals moved/closed in CRM", ["S01", "S02", "S03"], note="TOOL_UNAVAILABLE: crm — requires an export from Gev until Bitrix24 access exists."),
 PB("PB-04", "Conversion deterioration", "Call→sale, meeting→sale or lead→sale conversion falls", "investigate_sales_decline", ["sales_funnel_analysis", "channel_performance_analysis", "root_cause_analysis", "decision_support"],
    ["PBX calls & outcomes", "CRM leads by source & stage", "script/offer changes", "base quality"], ["S01", "S02"],
    ["compute conversion by agent/source/script", "check base quality (marketing base vs referrals)", "listen to sampled calls (senior's duty)", "check offer/tariff or competitor change"],
    ["Which stage and channel converts worse?", "Base quality or seller skill?", "Did the offer change?"],
    "Same activity, less revenue; CPL rises; telesales stop-rules trigger", "RECOMMEND coaching/script/base changes; pricing never", "Conversion below stop-rule levels (S03) → Gev",
    "Coaching + base fix + script test with owner/date", EXEC_FMT, "Հեռախոսային վաճառքի ավագ մասնագետ (1.4) / Մարքեթինգի ղեկավար (1.7) for leads", "1 week", "Conversion back to prior level in PBX/CRM", ["S01", "S02"]),
 PB("PB-05", "Churn increase", "Cancellations/abandonments up; save-list growing; 'churn is up'", "churn_increase", ["churn_analysis", "data_analysis", "root_cause_analysis", "decision_support"],
    ["churned subscribers with reason class, area, tariff, agreement type, tenure", "save list (S05)", "outages by area (network)", "complaints"], ["S05", "S06", "S02", "S04"],
    ["VERIFY definition (which of the 8 statuses count as churn — unconfirmed S18)", "segment by reason: technical/price/service/external (JD classifier)", "map to churn signals (irregular payment, no yearly agreement, outages in area…)", "check same-area concentration (mass outage) and technical-cause accumulation", "check retention calling actually happened (tracking GAP)"],
    ["Which reason class dominates?", "Is it concentrated in an area/PON?", "Monthly vs yearly agreements?", "Were at-risk subscribers contacted?"],
    "Base erosion; K-ACT decline (possibly the '2%/month' critical question U01)", "RECOMMEND; retention offers within approved list; benefits list changes → 3.1 → Gev", "Technical-cause accumulation → CTO; same-area mass cancellations → 3.1 + CTO immediately",
    "Named driver + retention action + technical fix; ownership decision request (C02)", EXEC_FMT, "CONFLICT C02 → Gev must name one owner (JD: 3.3 vacant / 3.1)", "Save list worked within the week; report by the 5th", "Retained count & churn % next month; tracking record exists", ["S02", "S05", "S06", "S08"]),
 PB("PB-06", "Revenue leakage suspicion", "Billed ≠ expected; unbilled active; wrong tariff; discounts; collection level down", "investigate_sales_decline", ["revenue_leakage_detection", "source_reconciliation", "root_cause_analysis", "decision_support"],
    ["billing vs technical active lists", "tariff assignments vs contracts", "discount/correction register", "payments by channel (inspectors!)"], ["S04", "S07", "S02"],
    ["reconcile active (network/OLT) vs billed (MikroBill)", "wrong tariff / unauthorized discount scan", "inspectors' cash entries vs system (Tasks #11)", "corrections anomalies"],
    ["Where does money leak: unbilled, wrong tariff, discount, uncollected cash?", "Who authorized?", "Is it systemic?"],
    "Direct revenue loss; audit exposure; @P1's Revenue Assurance ask (U02)", "RECOMMEND; corrections/write-offs need approval (thresholds UNKNOWN → APPROVAL_RULE_UNKNOWN)", "Any unauthorized discount or cash gap → P1 to Gev same day",
    "Leakage register + fix + control rule; approval request", EXEC_FMT, "Բիլինգի և եկամտի ղեկավար (4.1) — @P2 (DERIVED)", "Weekly leakage report cadence (roadmap)", "Cases closed and re-checked next cycle", ["S02", "S04", "S07"]),
 PB("PB-07", "Operations backlog increase", "Open installations/repairs growing; queue aging; 'backlog doubled'", "ops_backlog_growing", ["operations_kpi_monitoring", "backlog_management", "bottleneck_detection", "root_cause_analysis", "decision_support"],
    ["open applications by type/age/team (Bitrix24)", "install slots/day & staffing", "inflow (sales, faults)"], ["S01", "S02", "S03"],
    ["VERIFY inflow vs closure rate; aging distribution", "capacity: installation head VACANT, 3 senior installers VACANT; dispatcher absent (C09)", "bottleneck stage: assignment, materials/CPE, access, network signal", "SLA at risk list"],
    ["Inflow spike or capacity drop?", "Which stage is the bottleneck?", "Which SLAs will breach and when?", "Is sales outrunning install capacity (≥4 slots/day)?"],
    "Activation lead time ↑ → sales not counted, churn before start; strategy stop-rule freezes new sales", "RECOMMEND reprioritization; hiring/overtime → Gev", "Activation > 5 days or aging beyond SLA → P1; sales plan freeze rule",
    "Queue triage + capacity action (fill 2.3/2.4, temporary dispatcher) + freeze rule decision", EXEC_FMT, "Տեղադրման խմբի ղեկավար (2.3) VACANT → CTO (person UNKNOWN)", "Same day triage; capacity decision within the week", "Backlog and aging down in CRM export", ["S01", "S02", "S03"]),
 PB("PB-08", "SLA deterioration", "Install/repair/reactivation SLA attainment falls", "ops_backlog_growing", ["operations_kpi_monitoring", "bottleneck_detection", "root_cause_analysis", "decision_support"],
    ["SLA attainment by type/team", "breach reasons", "capacity"], ["S01", "S02"],
    ["confirm SLA definitions (values UNKNOWN — KPI_DEFINITION_MISSING for numbers)", "breach causes: capacity, materials, access, network, dispatch", "repeat visits share"],
    ["Which SLA, which team?", "Capacity or quality?", "Customer impact (complaints/churn)?"],
    "Churn driver (outage/repair signals), complaints, reputational", "RECOMMEND", "Breaches concentrated in one area → mass-outage path (NOC/CTO)",
    "Cause + fix + SLA value definition request", EXEC_FMT, "Group head (2.1/2.3/2.6) → CTO", "Weekly", "SLA attainment recovers", ["S01", "S02"]),
 PB("PB-09", "Repeated customer complaints", "Same complaint type/area recurring", "complaint_trend", ["customer_complaint_pattern_analysis", "root_cause_analysis", "decision_support"],
    ["complaints by type/area/cause/date", "related applications & repeats", "outages"], ["S02"],
    ["cluster by type & area", "link to technical cause (repeat visits, outage) or service (call quality) or billing (wrong charges)", "check weekly review by 3.1 happened", "RCA owner per cause"],
    ["What recurs and where?", "Technical, service or billing cause?", "Who owns the fix?"],
    "Churn, reputation (CEO escalation if legal/reputational)", "RECOMMEND; compensation/benefits → 3.1 within list", "Reputational/legal → CEO; same technical cause accumulating → CTO",
    "RCA + owner + deadline; complaint SLA definition request", EXEC_FMT, "Հաճախորդների սպասարկման ղեկավար (3.1)", "Weekly review; resolution within complaint deadline", "Complaint type frequency drops", ["S02"]),
 PB("PB-10", "Cross-department blocker", "Work stuck waiting on another unit (e.g., billing spec from @P2, JD OKs from heads)", "cross_department_blocker", ["waiting_for_tracking", "follow_up_management", "escalation_management"],
    ["waiting-for register (Tasks.xlsx owners/deadlines)", "the handoff definition in the process"], ["S09", "S02"],
    ["identify the process handoff and its owner (ownership map)", "age of the wait vs deadline", "is the blocker capability (cannot) or priority (won't)?", "escalation level per JD ladder"],
    ["Who exactly owes what since when?", "Can they deliver at all (@P1's 'ping-pong' warning)?", "What is the cost of waiting?"],
    "Delays cascade (e.g., reconciliation go-live; strategy meeting)", "Deputy drafts follow-up/escalation in Gev's voice; sending needs Gev's OK", "Past deadline or capability gap → escalate to Gev same day; Gev ↔ @P1 directly if critical",
    "Follow-up message + escalation option + alternative path", EXEC_FMT, "Requesting process owner; escalation to Gev", "Follow-up at deadline; escalate at +1 day", "Deliverable received (evidence) or decision to reassign", ["S07", "S09", "S15"]),
 PB("PB-11", "Important overdue task", "Tasks.xlsx row past deadline, especially @P1's critical asks", "daily_brief", ["deadline_management", "executive_prioritization", "follow_up_management"],
    ["Tasks.xlsx (deadline, owner, status)", "context from Journal"], ["S09", "S15"],
    ["confirm deadline source (@P1-set vs Deputy-proposed)", "impact: critical ask? (U01 is THE critical one)", "owner reachable? next step known?"],
    ["What slips if this stays open?", "New realistic date and who commits?", "Should Gev act personally?"],
    "Trust with @P1 (evidence EV-02: delivery credibility pressure)", "Deputy: remind early, propose date; commitments to @P1 only via Gev", "Critical ask overdue → interrupt Gev immediately",
    "Rescheduled date + owner + what Gev must do today", EXEC_FMT, "Task owner per Tasks.xlsx; Gev for @P1-facing items", "Signal before the deadline, not at it", "Status changed to Արված with evidence", ["S09", "S15"]),
 PB("PB-12", "Unresponsive owner", "No answer/progress from an owner after follow-ups", "broken_promise", ["follow_up_management", "waiting_for_tracking", "escalation_management"],
    ["follow-up history", "owner's manager per role model"], ["S02", "S09"],
    ["count follow-ups & dates", "check capability vs availability (@P2 overloaded — evidence EV-08)", "find manager in the escalation path", "alternative owner"],
    ["Is this a person or a system problem?", "Who is the manager?", "Can the work be reassigned?"],
    "Deadlines slip; @P1 sees inaction", "Deputy drafts; reassignment → Gev", "2 unanswered follow-ups → escalate to manager; 3 → Gev decision",
    "Escalation note + reassignment option", EXEC_FMT, "Owner's manager (role model) → Gev", "48h per follow-up cycle", "Response received or reassigned", ["S02", "S09"]),
 PB("PB-13", "Employee underperformance", "KPI attainment or JD evaluation direction below expectation ('X is underperforming')", "employee_underperformance", ["performance_gap_diagnosis", "root_cause_analysis", "decision_support"],
    ["role KPI values (targets UNKNOWN!)", "JD card expectations", "system/training context"], ["S01", "S02"],
    ["confirm the role's KPI set and weights (ROLE_KPIS)", "targets defined? if not → TARGET_UNKNOWN, judge on JD evaluation directions", "cause type: system (CRM down), training, process, person — never assume person first", "probation stage (month 1–3 rules)"],
    ["Which KPI, vs what target?", "System/training/process/person?", "What support was given?"],
    "Bonus tier; retention of staff; sales plan", "RECOMMEND; disciplinary/termination → manager → CEO order", "Stop rules for new sales hires (S03); repeated discipline → department head",
    "Cause + support plan + review date; decision request if termination", EXEC_FMT, "Direct manager per role model", "Review within 2 weeks", "KPI/behaviour evidence at review", ["S01", "S02", "S03"]),
 PB("PB-14", "Capacity shortage", "Vacancies/absences vs workload (13 critical vacancies)", "ops_backlog_growing", ["workload_analysis", "backlog_management", "decision_support"],
    ["vacancy list by priority (S01)", "workload/queues", "hiring pipeline"], ["S01", "S03"],
    ["map vacancies to processes they own (installation head, senior installers, billing specialist, sales specialists, D2D, telesales agents, L&R)", "which queues have no owner (C09 dispatcher)", "interim owner per JD ('մինչև հաստիքի համալրումը՝ CTO-ին')", "cost of filling (CONFIDENTIAL — overlay CV-12)"],
    ["Which shortage blocks revenue first?", "Interim owner?", "Hire, redistribute or freeze intake?"],
    "Sales cannot activate; retention has no owner; billing ops on one person", "RECOMMEND; hiring → Gev → CEO", "Critical vacancy blocking a P1 process → Gev decision this week",
    "Prioritized hiring/interim plan with cost (figures from the overlay when authorized)", EXEC_FMT, "Վաճառքի և գործառնական ղեկավար (Gev) with department heads", "Weekly", "Positions filled / interim assigned", ["S01", "S03"]),
 PB("PB-15", "Repeated operational failure", "Repeat visits, repeat faults in one segment, device failures after configuration", "complaint_trend", ["failure_rework_analysis", "root_cause_analysis", "decision_support"],
    ["repeat applications/visits by cause/team/segment", "RCA records", "CPE/firmware data"], ["S02"],
    ["cluster repeats (≤30 days) by cause", "RCA exists? approved by CTO?", "standard/checklist gap vs skill gap vs materials"],
    ["What fails repeatedly and why?", "Is the RCA closed?", "Standard or people?"],
    "Cost of rework; churn signal (outages); SLA", "RECOMMEND", "Same segment repeat → 2.6 RCA; mass → NOC/CTO",
    "RCA + corrective standard + training", EXEC_FMT, "Group head (2.1/2.3/2.6) → CTO", "RCA within the week", "Repeat rate down", ["S02"]),
 PB("PB-16", "Important decision pending", "Decision needed (tariff, strategy, staffing date, ownership) and stalled", "head_decision", ["decision_support", "risk_classification", "authority_checking", "approval_management"],
    ["issue, options, facts, deadline", "authority ladder"], ["S15", "S02"],
    ["classify: reversible/irreversible, material (price, salary, contract)", "who decides per ownership map (Gev vs @P1 vs CEO)", "cost of delay", "prepare options + recommendation"],
    ["What exactly must be decided, by whom, by when?", "What happens if not decided?", "Recommendation?"],
    "Open decisions block execution (retention owner, strategy, staffing effective date, billing BI)", "Deputy prepares; EXECUTE_MATERIAL/EXTERNAL only with Gev's token", "Decision blocking a P1 → interrupt Gev",
    "Decision brief: issue · impact · options · recommendation · Head action", EXEC_FMT, "Decision owner per ownership map", "By the dependent deadline", "Decision logged (decision_logging) and communicated", ["S15"]),
 PB("PB-17", "Missing management report", "Expected report not delivered (corporate monthly, billing daily/weekly, retention by the 5th)", "broken_promise", ["executive_reporting", "follow_up_management", "waiting_for_tracking"],
    ["routine calendar (RT-*)", "report owner (ownership map)"], ["S04", "S02", "S11"],
    ["is the report actually defined (owner, data source, format)? corporate report = GAP", "owner & due date", "data availability (systems Deputy cannot read)"],
    ["Defined or a wish?", "Who owes it?", "Can it be produced from available data?"],
    "Management blind; @P1's ask unanswered", "Deputy can draft from supplied data only; never fabricate numbers", "Report missing for a @P1 ask → Gev",
    "Definition request or follow-up; draft if data exists", EXEC_FMT, "Report owner or OWNER_UNKNOWN (corporate report)", "Report due date", "Report delivered (file/evidence)", ["S04", "S11", "S14"]),
 PB("PB-18", "Failed customer commitment", "Promise to a subscriber not met (activation date, repair, callback, PTP restoration)", "completed_no_evidence", ["completion_verification", "follow_up_management", "escalation_management"],
    ["application/task with promised date", "CRM status", "call log"], ["S02"],
    ["verify the promise and the miss (evidence, not narration)", "find the process step and owner that failed", "customer contacted? new date?", "repeat pattern?"],
    ["What was promised, by whom, what failed?", "Is the customer informed?", "Is this a pattern (PB-15/PB-09)?"],
    "Churn signal; complaint; reputation", "RECOMMEND; compensation/benefit → 3.1 within approved list", "VIP/legal/reputational → CEO path",
    "Recovery action + customer communication + process fix", EXEC_FMT, "Process owner (P-OPS-01/02, P-BILL-03) → 3.1 for customer contact", "Same day", "Customer confirmation recorded in CRM", ["S02"]),
]
