# -*- coding: utf-8 -*-
"""SOURCE INVENTORY — every business fact in the model cites one of these ids. Authority ranks decide precedence:
REFERENCE_APPROVED > ACTIVE_DRAFT/PROPOSAL/REGISTER > EVIDENCE (raw) > HISTORICAL. Two CURRENT sources that disagree = CONFLICT
(recorded in bm_company.CONFLICTS, never silently resolved). HISTORICAL never overrides CURRENT."""

AUTHORITY_RANK = {"REFERENCE_APPROVED": 5, "CHARTER": 5, "ACTIVE_REGISTER": 4, "ACTIVE_DRAFT": 3, "PROPOSAL": 3, "EVIDENCE": 2, "HISTORICAL": 1}

SOURCES = [
 {"source_id": "S01", "path": "02_Reference/People/Staffing-plan-2026-09-07.xlsx", "title": "Հաստիքացուցակ v2 — կառուցվածք, աշխատավարձ, վճարման մոդելներ, KPI (4 sheets)",
  "domain": "PEOPLE", "status": "APPROVED", "effective_date": "UNKNOWN (Oct 1 2026 proposed, unconfirmed — Open-questions #9)", "date": "2026-09-07",
  "owner": "Gev (author) · approved by @P1 2026-09-07 (evidence EV-09)", "source_type": "xlsx", "authority": "REFERENCE_APPROVED", "currency": "CURRENT",
  "conflicts": ["C05", "C08", "C09"], "notes": "Baseline for JD and everything else. 52 positions (25 filled, 27 vacant, 13 critical) + 2 ԱՁ + 3 execs = 57. Subtotal rows interleaved — never sum blindly."},
 {"source_id": "S02", "path": "01_Active/People/Job-descriptions-v1.1-2026-09-05.docx", "title": "Հաստիքների նկարագրություններ և որակավորման պահանջներ v1.1 (29 քարտ, 4 բաժին)",
  "domain": "PEOPLE", "status": "DRAFT_FINAL — awaiting each head's OK (due 2026-09-11)", "effective_date": "UNKNOWN (unsigned)", "date": "2026-09-05",
  "owner": "Gev (Տիրապետող՝ Վաճառքի և գործառնական ղեկավար); approver Գործադիր տնօրեն", "source_type": "docx", "authority": "ACTIVE_DRAFT", "currency": "CURRENT",
  "conflicts": ["C09", "C10"], "notes": "Aligned with S01 (29 titles identical, verified 2026-09-09). Deliberately excludes numeric KPI targets/weights."},
 {"source_id": "S03", "path": "01_Active/Sales/Sales-strategy-2026-09-09.docx", "title": "Վաճառքի կարճաժամկետ ռազմավարություն · Փուլ 1 — D2D և հեռավաճառք (Արմավիր, Մեծամոր, Էջմիածին)",
  "domain": "SALES", "status": "PROPOSAL — presented 2026-09-08; @P1 requires telesales + corporate sections; decision meeting Thu 2026-09-10", "effective_date": "NOT_APPROVED", "date": "2026-09-09",
  "owner": "Gev (+@P3 expected)", "source_type": "docx", "authority": "PROPOSAL", "currency": "CURRENT",
  "conflicts": ["C05"], "notes": "Numbers are proposal assumptions (7,000 AMD package, 18,000 connection cost, 70 activations/month, break-even month 5), not approved targets. No corporate section."},
 {"source_id": "S04", "path": "01_Active/Systems/Billing-roadmap-v2-2026-09-07.docx", "title": "HouseNet Billing Department — Տարեկան Roadmap 2026 (v2, document dated 17 March 2026)",
  "domain": "SYSTEMS/BILLING", "status": "ACTIVE — accepted as basis with 2 amendments by Gev (2026-09-09); @P1's acceptance of amendments not recorded", "effective_date": "UNKNOWN", "date": "2026-09-07",
  "owner": "Billing Head (roadmap owner); sent by @P1", "source_type": "docx", "authority": "ACTIVE_DRAFT", "currency": "CURRENT",
  "conflicts": ["C01", "C08"], "notes": "Defines reporting cadence, KPI dictionary (no targets), Bitrix24 workflows (planned Q1–Q2), prediction streams."},
 {"source_id": "S05", "path": "01_Active/Sales/Churn-save-list-2026-09-09.xlsx", "title": "Churn save list — 30 բաժանորդ, rule-based score (uncalibrated)",
  "domain": "SALES/RETENTION", "status": "WORKING DATA — to be worked by @P5 + @P2 from Mon 2026-09-14", "effective_date": "2026-09-09 (scored on)", "date": "2026-09-09",
  "owner": "@P1 (producer)", "source_type": "xlsx", "authority": "EVIDENCE", "currency": "CURRENT",
  "conflicts": [], "notes": "Criteria: score ≥70, hot signals ≥3, coverage ≥60%, limit 50. Contains subscriber PII (RESTRICTED) — payload never enters the model; aggregates only in overlay EV-01."},
 {"source_id": "S06", "path": "04_Sources/Screenshots/Churn-risk-signals-2026-09-09.jpeg", "title": "Churn risk — 12 rule signals with published weights (of 100)",
  "domain": "SALES/RETENTION", "status": "EVIDENCE (@P1's team model)", "effective_date": "2026-09-09", "date": "2026-09-09",
  "owner": "@P1's team", "source_type": "image", "authority": "EVIDENCE", "currency": "CURRENT",
  "conflicts": [], "notes": "Gev proposed additions: complaint calls/month; separate treatment for yearly-agreement subscribers (not yet in model)."},
 {"source_id": "S07", "path": "04_Sources/Whatsapp/Principal-2026-09-09/chat.md", "title": "WhatsApp @P1 ↔ Gev, 2026-09-05 … 09-09 11:29",
  "domain": "MANAGEMENT", "status": "RAW EVIDENCE", "effective_date": "n/a", "date": "2026-09-09",
  "owner": "@P1 / Gev", "source_type": "chat export", "authority": "EVIDENCE", "currency": "CURRENT",
  "conflicts": ["C02", "C03"], "notes": "Voice messages and images are missing from the export (Revenue Assurance 09-07 20:14/20:16; churn signals 09-09 12:51/12:52)."},
 {"source_id": "S08", "path": "04_Sources/Whatsapp/Principal-2026-09-09-afternoon/chat.md", "title": "WhatsApp @P1 ↔ Gev, 2026-09-09 00:39 … 13:10",
  "domain": "MANAGEMENT", "status": "RAW EVIDENCE", "effective_date": "n/a", "date": "2026-09-09",
  "owner": "@P1 / Gev", "source_type": "chat export", "authority": "EVIDENCE", "currency": "CURRENT", "conflicts": ["C02", "C03"], "notes": "Retention flow, churn lists, save-list handoff."},
 {"source_id": "S09", "path": "Tasks.xlsx", "title": "Առաջադրանքներ — live task register (15 items, hand-edited by Gev)",
  "domain": "MANAGEMENT", "status": "LIVE REGISTER", "effective_date": "n/a", "date": "2026-09-09",
  "owner": "Gev", "source_type": "xlsx", "authority": "ACTIVE_REGISTER", "currency": "CURRENT", "conflicts": [], "notes": "Owners, deadlines and statuses of @P1's asks; read by daily_briefing."},
 {"source_id": "S10", "path": "01_Active/Operations/Open-questions.md", "title": "ՀԱՐՑԵՐ — 25 open questions to Gev (people roles, systems access, dates)",
  "domain": "MANAGEMENT", "status": "OPEN — 2 of 25 answered", "effective_date": "n/a", "date": "2026-09-10",
  "owner": "Deputy → Gev", "source_type": "md", "authority": "ACTIVE_REGISTER", "currency": "CURRENT", "conflicts": [], "notes": "Answered: #3 (churn voice = signal list request), #5 (keep Gev's system)."},
 {"source_id": "S11", "path": "03_Completed/Delivery-schedule-2026-09-09.xlsx", "title": "Գրաֆիկ — what Gev delivers when (sent to @P1 2026-09-09) + Gev's two billing positions",
  "domain": "MANAGEMENT", "status": "SENT — commitments snapshot", "effective_date": "2026-09-09", "date": "2026-09-09",
  "owner": "Gev", "source_type": "xlsx/txt", "authority": "ACTIVE_REGISTER", "currency": "CURRENT", "conflicts": ["C01"], "notes": "Also 03_Completed/Delivery-schedule-whatsapp-2026-09-09.txt (the sent text)."},
 {"source_id": "S12", "path": "05_Archive/Drafts-2026-09-09/Principal-requirements-2026-09-09.md", "title": "@P1-ի պահանջները — 44 asks in his words (09-05…09-09) + annotated xlsx",
  "domain": "MANAGEMENT", "status": "SUPERSEDED by Tasks.xlsx", "effective_date": "n/a", "date": "2026-09-09",
  "owner": "Deputy", "source_type": "md/xlsx", "authority": "HISTORICAL", "currency": "HISTORICAL", "conflicts": [], "notes": "History only; verbatim quotes remain useful as evidence."},
 {"source_id": "S13", "path": "05_Archive/Drafts-2026-09-09/Task-workbook-8-sheet-2026-09-09.xlsx", "title": "Old 8-sheet task workbook (+Schedule-questions, Whatsapp-readme)",
  "domain": "MANAGEMENT", "status": "SUPERSEDED", "effective_date": "n/a", "date": "2026-09-09",
  "owner": "Deputy", "source_type": "xlsx/md", "authority": "HISTORICAL", "currency": "HISTORICAL", "conflicts": [], "notes": "Never used for current truth."},
 {"source_id": "S14", "path": "Actions.md", "title": "ԱՆԵԼԻՔՆԵՐ — Deputy's internal to-dos on documents/system",
  "domain": "MANAGEMENT", "status": "LIVE", "effective_date": "n/a", "date": "2026-09-10",
  "owner": "Deputy", "source_type": "md", "authority": "ACTIVE_REGISTER", "currency": "CURRENT", "conflicts": [], "notes": "Open: JD+staffing single doc, ԱՁ JDs, corporate section, KPI sheet completeness, manager chain, Bitrix24 tasks not in register."},
 {"source_id": "S15", "path": ".claude/docs/Job-description.md", "title": "Deputy — Job Description & Operating Charter (53 sections): how Gev wants information, rhythm, authority",
  "domain": "MANAGEMENT", "status": "APPROVED 2026-09-10", "effective_date": "2026-09-10", "date": "2026-09-10",
  "owner": "Gev", "source_type": "md", "authority": "CHARTER", "currency": "CURRENT", "conflicts": [], "notes": "Executive output format, P1–P4 prioritization, daily/weekly/monthly rhythm, interruption rules."},
]
